---
permalink: windows/concept_cloning_methods.html 
sidebar: sidebar 
keywords: clone, cloning, method, database 
summary: Es posible clonar una base de datos mediante uno de estos dos métodos. El método seleccionado afecta a la operación de creación de clon. 
---
= Métodos de clonación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible clonar una base de datos mediante uno de estos dos métodos. El método seleccionado afecta a la operación de creación de clon.

En la siguiente tabla se describen los métodos de clonado y su efecto en la operación clone create y su opción -reserve. Una LUN se puede clonar mediante cualquiera de los dos métodos.

|===
| Método de clonación 


| Descripción 


| clone create -reserve 


 a| 
Clonado de LUN



 a| 
Se crea un nuevo LUN clon en el mismo volumen.



 a| 
Cuando -reserve para una LUN está establecida en yes, se reserva espacio para todo el tamaño de LUN dentro del volumen.



 a| 
Clonado de volúmenes



 a| 
Se crea un nuevo FlexClone y la LUN clonada existe dentro del nuevo volumen clonado. Utiliza la tecnología FlexClone.



 a| 
Cuando -reserve para un volumen está establecida en yes, se reserva espacio para todo el tamaño del volumen dentro del agregado.

|===