---
permalink: windows/concept_preinstallation_tasks.html 
sidebar: sidebar 
keywords: install, snapmanager, oracle, environment, preinstallation, task 
summary: Antes de instalar SnapManager para Oracle, debe realizar algunas tareas adicionales para configurar el entorno. Las tareas que debe realizar dependen del sistema operativo, los componentes de Oracle y la versión de la base de datos que desee utilizar. 
---
= Tareas de preinstalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar SnapManager para Oracle, debe realizar algunas tareas adicionales para configurar el entorno. Las tareas que debe realizar dependen del sistema operativo, los componentes de Oracle y la versión de la base de datos que desee utilizar.

* Instalar el sistema operativo con licencia con los parches adecuados.
* Defina los idiomas del sistema operativo y de la base de datos Oracle en inglés.
+
Por ejemplo, para establecer el idioma de la base de datos Oracle en inglés ASSIGN NLS_LANG = AMERICAN_AMERICA.WE8MSWIN1252. Para obtener más información acerca de cómo configurar el idioma, consulte la sección _Troubleshooting SnapManager for Oracle_.

* Instale Oracle Recovery Manager (RMAN) si desea utilizar RMAN con SnapManager para Oracle.
* Instalar Data ONTAP con licencias habilitadas para SnapRestore y los protocolos compatibles como Fibre Channel (FC) y Internet Small Computer System Interface (iSCSI) en todos los sistemas de almacenamiento.
* Instale los siguientes parches de Oracle, si utiliza las bases de datos Oracle 11.2.0.2 y 11.2.0.3:
+
** 13413167 para Windows de 32 bits
** 13555974 para Windows de 64 bits




*Información relacionada*

xref:reference_troubleshooting_snapmanager.adoc[Resolución de problemas de SnapManager]

http://support.netapp.com/NOW/products/interoperability/["Matriz de interoperabilidad de NetApp: support.netapp.com/NOW/products/interoperability"]

http://media.netapp.com/documents/tr-3761.pdf["Prácticas recomendadas de SnapManager para Oracle: media.netapp.com/documents/tr-3761.pdf"]
