---
permalink: windows/reference_the_smosmsap_schedule_create_command.html 
sidebar: sidebar 
keywords: smo, schedule, create, command, backup, specific, time 
summary: Es posible utilizar el comando schedule create para programar la creación de un backup en un momento específico. 
---
= El comando smo schedule create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible utilizar el comando schedule create para programar la creación de un backup en un momento específico.



== Sintaxis

[listing]
----

        smo schedule create
-profile profile_name
\[-full\{-auto \| -online \| -offline\}
\[-retain -hourly \| -daily \| -weekly \| -monthly \| -unlimited\]
\[-verify\]\] |
\[-data \[\[-files files \[files\]\] \|
\[-tablespaces tablespaces \[tablespaces\]\] \{-auto \| -online \| -offline\}
\[-retain -hourly \| -daily \| -weekly \| -monthly \| -unlimited\]
\[-verify\]\] |
\[-archivelogs\]}
\[-label label\]
\[-comment comment\]

\[-backup-dest path1 \[ , path2\]\]
\[-exclude-dest path1 \[ , path2\]\]
\[-prunelogs \{-all \| -until-scn until-scn \| -until -date  yyyy-MM-dd:HH:mm:ss\] \| -before \{-months \| -days \| -weeks \| -hours}}
-prune-dest prune_dest1,\[prune_dest2\]\]
-schedule-name schedule_name
\[-schedule-comment schedule_comment\]
-interval \{-hourly \| -daily \| -weekly \| -monthly \| -onetimeonly\}
-cronstring cron_string
-start-time \{start_time <yyyy-MM-dd HH:mm\>\}
-runasuser runasuser
\[-taskspec taskspec\]
-force
\[-quiet \| -verbose\]
----


== Parámetros

* *-profile profile_name*
+
Especifica el nombre del perfil relacionado con la base de datos para la que desea programar el backup. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *-opción automática*
+
Si la base de datos está en estado montado o sin conexión, SnapManager realiza un backup sin conexión. Si la base de datos está en estado abierto o en línea, SnapManager realiza un backup en línea. Si se utiliza la opción -force con la opción -offline, SnapManager fuerza un backup sin conexión aunque la base de datos esté actualmente en línea.

* *-opción en línea*
+
Especifica un backup de base de datos en línea.

* *-opción sin conexión*
+
Especifica un backup sin conexión mientras la base de datos está en estado de apagado. Si la base de datos está en estado abierto o montado, el backup genera errores. Si se utiliza la opción -force, SnapManager intenta modificar el estado de la base de datos para cerrar la base de datos con el fin de realizar una copia de seguridad sin conexión.

* *-opción completa*
+
Realiza un backup de toda la base de datos. Esto incluye todos los datos, registros archivados y archivos de control. Se realiza una copia de seguridad de los redo logs archivados y de los archivos de control, independientemente del tipo de copia de seguridad que realice. Si se desea realizar un backup solo de una parte de la base de datos, se deben utilizar la opción -files o -tablespaces.

* *-lista de archivos*
+
Realiza un backup solo de los archivos de datos especificados, además de los archivos de registro y control archivados. Separe la lista de nombres de archivo con espacios. Si la base de datos está en estado abierto, SnapManager verifica que los espacios de tablas apropiados se encuentren en modo de backup en línea.

* *-tablespaces*
+
Realiza un backup solo de los espacios de tablas de la base de datos especificados, además de los archivos de registro y control archivados. Separe los nombres de tablespace con espacios. Si la base de datos está en estado abierto, SnapManager verifica que los espacios de tablas apropiados se encuentren en modo de backup en línea.

* *-nombre de etiqueta*
+
Especifica un nombre opcional para este backup. Este nombre debe ser único dentro del perfil. El nombre puede contener letras, números, guiones bajos (_) y guiones (-). No puede comenzar con un guión.

+
Si no se especifica una etiqueta, SnapManager crea una etiqueta predeterminada en el formato scope_type_date:

+
** El ámbito es F indicar un backup completo o P para indicar un backup parcial.
** El tipo es C para indicar una copia de seguridad sin conexión (en frío), H para indicar una copia de seguridad en línea (activa) o A para indicar una copia de seguridad automática, por ejemplo, P_A_20081010060037IST.
** Fecha es el año, el mes, el día y la hora de la copia de seguridad.
+
SnapManager se usa un reloj de 24 horas.



+
Por ejemplo, si realizó un backup completo con la base de datos sin conexión el 16 de enero de 2007, a las 5:45:16 Hora estándar del este, SnapManager crearía la etiqueta F_C_20070116174516EST.

* *-cadena de comentario*
+
Especifica un comentario opcional para describir esta copia de seguridad. La cadena debe escribirse entre comillas simples (').

+

NOTE: Algunos vaciados pelan entre comillas. Si esto es cierto para el shell, debe incluir la comillas con una barra diagonal inversa (\). Por ejemplo, es posible que deba introducir: `\' this is a comment\'`.

* *-verificar opción*
+
Verifica que los archivos de la copia de seguridad no están dañados ejecutando la utilidad oracle dbv.

+

NOTE: Si se especifica la opción -Verify, la operación de backup no se completará hasta que finalice la operación de verificación.

* *-opción de fuerza*
+
Fuerza un cambio de estado si la base de datos no está en el estado correcto. Por ejemplo, SnapManager puede cambiar el estado de la base de datos de en línea a sin conexión, según el tipo de backup especificado y el estado en el que está la base de datos.

+
** Si la instancia local está en estado de apagado y al menos una instancia está abierta, puede cambiar la instancia local a montada mediante la opción -force .
** Si no hay ninguna instancia abierta, puede cambiar la instancia local a abierta mediante la opción -force.


* *-retener { -hora | -diario | -semanal | -mensual | -ilimitado}*
+
Especifica si el backup se debe retener por hora, día, semana, mes o ilimitada. Si no se especifica la opción -retain, la clase de retención predeterminada es -Hourly. Para retener las copias de seguridad para siempre, utilice la opción -Unlimited. La opción -Unlimited hace que el backup no sea apto para que lo elimine la política de retención.

* *-archivelogs*
+
Especifica la creación de un backup de registro de archivos.

* *-backup-más extraño path1, [, [path2]]*
+
Especifica los destinos de registros de archivos para el backup de registros de archivos.

* *-exclude-más extraño path1, [, [path2]]*
+
Especifica los destinos de registro de archivos que se excluirán de la copia de seguridad.

* *-prunelogs {-all | -until-scnuntil-scn | -until-dateyyyy-MM-dd:HH:mm:ss | -before {-meses | -días | -semanas | -horas}*
+
Especifica si se eliminarán los archivos de registro de archivos de los destinos de registro de archivos en función de las opciones proporcionadas al crear un backup. La opción -all elimina todos los archivos de registro de archivos de los destinos de registro de archivos. La opción -until-scn elimina los archivos de registro de archivos hasta que se especifique un número de cambio de sistema (SCN). La opción -until-date elimina los archivos de registro de archivos hasta el periodo de tiempo especificado. La opción -before elimina los archivos de registro de archivos antes del periodo de tiempo especificado (días, meses, semanas, horas).

* *-nombre-horario nombre_horario*
+
Especifica el nombre que se proporcionará para la programación.

* *-schedule-comentario schedule_comment*
+
Especifica un comentario opcional que se va a describir acerca de la programación del backup.

* *-interval { -time | -daily | -semanal | -mensual | -onetimeonly}*
+
Especifica el intervalo de tiempo mediante el cual se crean los backups. Se puede programar el backup cada hora, día, semana, mes o solo una vez.

* *-cronstring cron_string*
+
Especifica la programación del backup mediante cronstring. Las expresiones cron se utilizan para configurar instancias de CronTrigger. Las expresiones cron son cadenas que se componen de las siguientes subexpresiones:

+
** 1 se refiere a segundos.
** 2 se refiere a minutos.
** 3 se refiere a horas.
** 4 se refiere a un día en un mes.
** 5 se refiere al mes.
** 6 se refiere a un día en una semana.
** 7 se refiere al año (opcional).


* *-hora de inicio aaaa-MM-dd HH:mm*
+
Especifica la hora de inicio de la operación programada. La hora de inicio de la programación debe incluirse en el formato aaaa-MM-dd HH:mm.

* *-runasuser runasuser*
+
Especifica si se cambia el usuario (usuario raíz o usuario de Oracle) de la operación de backup programada mientras se programa el backup.

* *-tasktaskspec*
+
Especifica el archivo XML de especificación de la tarea que se puede utilizar para la actividad de preprocesamiento o la actividad de posprocesamiento de la operación de copia de seguridad. La ruta completa del archivo XML debe proporcionarse con la opción -taskspec .

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.


