---
permalink: windows/reference_the_smosmsapprofile_sync_command.html 
sidebar: sidebar 
keywords: command, load, profile-to-repository, mapping, repository, file, directory, smo 
summary: Este comando carga las asignaciones de perfil a repositorio para ese repositorio en un archivo del directorio inicial en el host local. 
---
= El comando smo profile SYNC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando carga las asignaciones de perfil a repositorio para ese repositorio en un archivo del directorio inicial en el host local.



== Sintaxis

[listing]
----

        smo profile sync
-repository
-dbname repo_service_name
-host repo_host
-port repo_port
-login
-username repo_username
				\[-quiet \| -verbose\]
----


== Parámetros

* *-repositorio*
+
Las opciones que siguen a -repository especifican los detalles de la base de datos para el repositorio.

* *-dbname repo_service_name*
+
Especifica la base de datos del repositorio para el perfil que se va a sincronizar.

* *-host*
+
Especifica el host de la base de datos.

* *-puerto*
+
Especifica el puerto para el host.

* *-login*
+
Especifica el proceso de inicio de sesión para el usuario host.

* *-nombre de usuario*
+
Especifica el nombre de usuario para el host.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el siguiente ejemplo se muestra el resultado del comando para sincronizar las asignaciones de perfil a repositorio de la base de datos.

[listing]
----
smo profile sync -repository -dbname smrepo -host Host2 -port 1521 -login -username user2
SMO-12345 [INFO ]: Loading profile mappings for repository "user2@Host2:smrepo" into cache for OS User "admin".
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----