---
permalink: windows/reference_the_smosmsapbackup_update_command.html 
sidebar: sidebar 
keywords: run, backup, update, command, retention, policy, smo 
summary: Puede ejecutar el comando backup update para actualizar la política de retención de backups. 
---
= El comando de actualización de backup de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando backup update para actualizar la política de retención de backups.



== Sintaxis

[listing]
----

        smo backup update
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id guid\]
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\}\]
\[-comment comment_text\]
[-quiet | -verbose]
----


== Parámetros

* *-profile profile_name*
+
Especifica el perfil para el que se actualizarán las copias de seguridad. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *-id guid*
+
Verifica el backup con el GUID especificado. SnapManager genera el GUID cuando se crea un backup. Puede utilizar el comando smo backup list para mostrar el GUID de cada backup.

* * etiqueta*
+
Especifica la etiqueta de backup y el alcance del backup como archivo de datos o registro de archivos.

* *-data*
+
Especifica los archivos de datos.

* *-archivelogs*
+
Especifica los archivos de registro de archivos.

* *-comment_text*
+
Introduzca texto (hasta 200 caracteres) acerca de la actualización de copia de seguridad. Puede incluir espacios.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.

* *-retener {-hora | -diario | -semanal | -mensual | -ilimitado}*
+
Especifica si el backup se debe retener por hora, día, semana, mes o ilimitada. Si no se especifica -retain, la clase de retención predeterminada es -Hourly. Para retener las copias de seguridad para siempre, utilice la opción -Unlimited. La opción -Unlimited hace que la copia de seguridad no sea elegible para su eliminación.





== Ejemplo

En el ejemplo siguiente se actualiza el backup para establecer la política de retención en Unlimited:

[listing]
----
smo backup update -profile SALES1 -label full_backup_sales_May
-retain -unlimited -comment save_forever_monthly_backup
----
*Información relacionada*

xref:task_changing_the_backup_retention_policy.adoc[Cambiar la política de retención de backups]

xref:task_retaining_backups_forever.adoc[Retención permanente de backups]

xref:task_freeing_or_deleting_retention_policy_exempt_backups.adoc[Liberar o eliminar backups exentos de la política de retención]
