---
permalink: windows/reference_the_smosmsapbackup_list_command.html 
sidebar: sidebar 
keywords: run, backup, list, command, display, information, profile, retention, protection, status, smo 
summary: Puede ejecutar el comando backup list para ver información sobre los backups de un perfil, incluida la información sobre la clase de retención y el estado de protección. 
---
= El comando smo backup list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando backup list para ver información sobre los backups de un perfil, incluida la información sobre la clase de retención y el estado de protección.



== Sintaxis

[listing]
----

        smo backup list
-profile profile_name
-delimiter character
[-data | -archivelogs | -all]
\[-quiet \| -verbose\]
----


== Parámetros

* *-profile profile_name*
+
Especifica el perfil para el que desea mostrar las copias de seguridad. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* * carácter delimitador*
+
Muestra cada fila en una línea diferente. Los atributos de la fila están separados por el carácter especificado.

* *-data*
+
Especifica los archivos de datos.

* *-archivelogs*
+
Especifica los archivos de registro de archivos.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola. Incluye la opción -verbose para mostrar los ID de backup.





== Ejemplo

En el ejemplo siguiente se enumeran las copias de seguridad del perfil SALES1:

[listing]
----
smo backup list -profile SALES1 -verbose
Start Date          Status  Scope  Mode    Primary  Label      Retention   Protection
------------------- ------- ------ ------- -------- -----      --------    ----------
2007-08-10 14:12:31 SUCCESS FULL   ONLINE  EXISTS   backup2    HOURLY      NOT REQUESTED
2007-08-05 12:08:37 SUCCESS FULL   ONLINE  EXISTS   backup4    UNLIMITED   NOT REQUESTED
2007-08-04 22:03:09 SUCCESS FULL   ONLINE  EXISTS   backup6    UNLIMITED   NOT REQUESTED
----
*Información relacionada*

xref:task_viewing_a_list_of_backups.adoc[Ver una lista de backups]
