---
permalink: windows/reference_the_smosmsap_clone_update_command.html 
sidebar: sidebar 
keywords: command, update, information, clone, comment, smo 
summary: Este comando actualiza información acerca del clon. Puede actualizar el comentario. 
---
= El comando smo clone update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando actualiza información acerca del clon. Puede actualizar el comentario.



== Sintaxis

[listing]
----

        smo clone update
-profile profile_name
\[-label label \| -id id\]
-comment  commment_text
\[-quiet \| -verbose\]
----


== Parámetros

* *-profile profile_name*
+
Especifica el nombre del perfil que contiene el clon que desea actualizar. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *-id*
+
Especifica el ID del clon. SnapManager genera el ID cuando crea un clon. Use el comando smo clone list para mostrar el ID de cada clon.

* * etiqueta*
+
Especifica la etiqueta del clon.

* *-comentario*
+
Muestra el comentario introducido en la creación del clon. Este es un parámetro opcional.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el siguiente ejemplo se actualiza el comentario del clon.

[listing]
----
smo clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT -comment See updated clone
----