---
permalink: windows/reference_snapmanager_configuration_parameters.html 
sidebar: sidebar 
keywords: provide, list, configuration, parameter, edit, requirement 
summary: SnapManager proporciona una lista de parámetros de configuración que se pueden editar en función de sus requisitos. Los parámetros de configuración se almacenan en el archivo smo.config. Sin embargo, es posible que el archivo smo.config no contenga todos los parámetros de configuración admitidos. Puede agregar los parámetros de configuración, según sus necesidades. 
---
= Parámetros de configuración de SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager proporciona una lista de parámetros de configuración que se pueden editar en función de sus requisitos. Los parámetros de configuración se almacenan en el archivo smo.config. Sin embargo, es posible que el archivo smo.config no contenga todos los parámetros de configuración admitidos. Puede agregar los parámetros de configuración, según sus necesidades.

En la siguiente tabla, se enumeran todos los parámetros de configuración de SnapManager compatibles y también se explica cuándo usar estos parámetros:

|===


| Parámetros | Descripción 


 a| 
* retain.hourly.count
* retain.hourly.duration
* retenga.monthly.count
* retain.monthly.duration

 a| 
Estos parámetros configuran la política de retención al crear un perfil. Por ejemplo, puede asignar los siguientes valores:retain.Hourly.count = 12

retain.hourly.duration = 2

retenga.monthly.count = 2

retain.monthly.duration = 6



 a| 
Restore.temporaryVolumeName
 a| 
Este parámetro asigna un nombre al volumen temporal. Cuando SnapManager utiliza el método indirecto para restaurar datos desde el almacenamiento secundario, requiere un volumen de desecho en el almacenamiento principal para conservar una copia temporal de los datos hasta que se copian en los archivos de la base de datos y se recupera la base de datos. No hay un valor predeterminado. Si no especifica un valor, debe introducir un nombre en el comando restore que utilice el método indirecto. Por ejemplo, puede asignar los siguientes valores:restore.temporaryVolumeName = smo_temp_volume



 a| 
host.credenciales.persistir
 a| 
Este parámetro permite que SnapManager almacene credenciales del host. De manera predeterminada, las credenciales del host no se almacenan. Sin embargo, se deben almacenar las credenciales de host si tiene un script personalizado que se ejecuta en un clon remoto y requiere acceso a un servidor remoto. Para habilitar el almacenamiento de credenciales de host, asigne TRUE al host.credenciales.persistir. SnapManager cifra y guarda las credenciales del host.



 a| 
RestorePlanMaxFilesDisjugado
 a| 
Este parámetro permite definir el número máximo de archivos que se mostrarán en la vista previa de la restauración.de forma predeterminada, SnapManager muestra un máximo de 20 archivos en la vista previa de la restauración. Sin embargo, puede cambiar a un valor mayor que 0. Por ejemplo, puede asignar el siguiente valor:

* RestorePlanMaxFilesDisjugado = 30



NOTE: Si especifica un valor no válido, se muestra el número predeterminado de archivos.



 a| 
snapshot.list.timeout.min
 a| 
Este parámetro permite definir el tiempo en minutos durante el cual SnapManager debe esperar a que se ejecute el comando snap list al realizar cualquier operación de SnapManager.de forma predeterminada, SnapManager espera 30 minutos. Sin embargo, puede cambiar a un valor mayor que 0. Por ejemplo, puede asignar el siguiente valor:

* snapshot.list.timeout.min = 40



NOTE: Si especifica un valor no válido, se utiliza el valor predeterminado.

Para cualquier operación de SnapManager, si el tiempo de ejecución del comando snap list supera el valor asignado a snapshot.list.timeout.min, la operación genera un mensaje de error de tiempo de espera.



 a| 
PruneIfFileExistsInOtherDestination
 a| 
Este parámetro de eliminación permite definir el destino de los archivos de registros de archivos. Los archivos de registro de archivos se almacenan en varios destinos. Al eliminar los archivos de registro de archivos, SnapManager debe conocer el destino de los archivos de registro de archivos. Los posibles valores que puede asignar son los siguientes:

* Cuando desee quitar los archivos de registro de archivo de un destino especificado, debe asignar false a pruneIfFileExistsInOtherDestination.
* Cuando desee quitar los archivos de registro de archivo de un destino externo, debe asignar true a pruneIfFileExistsInOtherDestination.




 a| 
prune.archivelogs.backedup.from.otherdestination
 a| 
Este parámetro de eliminación permite reducir los archivos de registro de archivos de los que se ha realizado una copia de seguridad desde los destinos de registro de archivos especificados o del que se ha realizado una copia de seguridad desde destinos de registros de archivos externos. Los posibles valores que puede asignar son los siguientes:

* Si desea comprimir los archivos de registro de archivos desde los destinos especificados y si se realiza un backup de los archivos de registro de archivos desde los destinos especificados mediante -prune-dest, debe asignar false a prune.archivelogs.backedup.from.otherdestination.
* Si desea comprimir los archivos de registro de archivos desde destinos especificados y si se realiza una copia de seguridad de los archivos de registro de archivos al menos una vez desde cualquiera de los otros destinos, debe asignar true a prune.archivelogs.backedup.from.otherdestination.




 a| 
Maximum.archivvelog.files.torune.atATime
 a| 
Este parámetro de eliminación permite definir el número máximo de archivos de registro de archivos que puede recortar en un momento dado. Por ejemplo, puede asignar el siguiente valor:Maximum.archivvelog.files.torune.atATime = 998


NOTE: El valor que se puede asignar a Maximum.archivvelog.files.torune.atATime debe ser inferior a 1000.



 a| 
archvelogs.consolidate
 a| 
Este parámetro permite a SnapManager liberar las copias de seguridad duplicadas de registros de archivo si asigna true a archivvelogs.consolidate.



 a| 
suffix.backup.label.with.logs
 a| 
Este parámetro permite especificar el sufijo que se desea añadir para diferenciar los nombres de etiqueta del backup de datos y del backup de registros de archivo.por ejemplo, al asignar registros al sufijo.backup.label.with.logs, se añade _logs como sufijo a la etiqueta de backup de registros de archivo. La etiqueta de backup del registro de archivos debería ser arch_logs.



 a| 
backup.archivelogs.beyond.missingfiles
 a| 
Este parámetro permite que SnapManager incluya los archivos de registro de archivos faltantes en el backup. Los archivos de registro de archivos que no existen en el sistema de archivos activo no se incluyen en la copia de seguridad. Si desea incluir todos los archivos de registro de archivos, incluso los que no existen en el sistema de archivos activo, debe asignar true a backup.archivelogs.beyond.missingfiles.

Puede asignar false para ignorar los archivos de registro de archivos que faltan.



 a| 
srvctl.timeout
 a| 
Este parámetro permite definir el valor de tiempo de espera para el comando srvctl. *Nota:* el control de servidor (SRVCTL) es una utilidad para administrar instancias de RAC.

Cuando SnapManager tarda más tiempo en ejecutar el comando srvctl que el valor timeout, la operación SnapManager produce un error con este mensaje de error: Error: Se ha agotado el tiempo de espera mientras se ejecuta el comando: Srvctl status.



 a| 
Snapshot.restore.storageNameCheck
 a| 
Este parámetro permite a SnapManager ejecutar la operación de restauración con copias de Snapshot que se crearon antes de migrar desde operaciones de Data ONTAP en 7-Mode a Clustered Data ONTAP.el valor predeterminado asignado al parámetro es FALSE. Si ha realizado la migración desde Data ONTAP funcionando en 7-Mode a Clustered Data ONTAP, pero quiere utilizar las copias Snapshot creadas antes de la migración, establezca snapshot.restore.storageNameCheck=true.



 a| 
services.common.disableAbort
 a| 
Este parámetro deshabilita la limpieza tras el fallo de las operaciones de ejecución prolongada. Puede establecer un ejemplo services.common.disableAbort=true.For, si está realizando una operación de clonado que se ejecuta mucho y, a continuación, se produce un error debido a un error de Oracle, es posible que no desee limpiar el clon. Si establece services.common.disableAbort=true, no se eliminará el clon. Puede corregir el problema de Oracle y reiniciar la operación de clonado desde el punto en que falló.



 a| 
* backup.sleep.dnfs.layout
* backup.sleep.dnfs.secs

 a| 
Estos parámetros activan el mecanismo de suspensión en el diseño Direct NFS (dNFS). Después de crear la copia de seguridad de los archivos de control con dNFS o un sistema de archivos de red (NFS), SnapManager intenta leer los archivos de control, pero es posible que no se encuentren los archivos.para habilitar el mecanismo de suspensión, asegúrese de que backup.sleep.dnfs.Layout=true. El valor predeterminado es TRUE.

Al activar el mecanismo de suspensión, debe asignar el tiempo de suspensión a backup.sleep.dnfs.secs. El tiempo de inactividad asignado es en segundos y el valor depende de su entorno. El valor predeterminado es 5 segundos.

Por ejemplo:

* backup.sleep.dnfs.layout=true
* backup.sleep.dnfs.secs=2




 a| 
* override.default.backup.pattern
* new.default.backup.pattern

 a| 
Cuando no se especifica la etiqueta de backup, SnapManager crea una etiqueta de backup predeterminada. Estos parámetros de SnapManager permiten personalizar la etiqueta de copia de seguridad predeterminada.para personalizar la etiqueta de copia de seguridad, asegúrese de que el valor de override.default.backup.pattern se establece en true. El valor predeterminado es FALSE.

Para asignar el nuevo patrón de la etiqueta de backup, se pueden asignar palabras clave como el nombre de la base de datos, el nombre del perfil, el ámbito, el modo y el nombre del host a new.default.backup.pattern. Las palabras clave se deben separar con un guión bajo. Por ejemplo, new.default.backup.pattern=dbname_profile_hostname_scope_mode.


NOTE: La Marca de hora se incluye automáticamente al final de la etiqueta generada.



 a| 
allow.underscore.in.clone.sid
 a| 
Oracle admite el uso de guion bajo en el SID de clonado de Oracle 11gR2. Este parámetro SnapManager permite incluir un guión bajo en el nombre del SID del clon.para incluir un guión bajo en el nombre del SID del clon, asegúrese de que el valor de allow.underscore.in.clone.sid se configure en TRUE. El valor predeterminado es TRUE.

Si utiliza una versión de Oracle anterior a Oracle 11gR2 o si no desea incluir un guión bajo en el nombre del SID del clon, establezca el valor en FALSE.



 a| 
oracle.parameters.with.comma
 a| 
Este parámetro permite especificar todos los parámetros de Oracle que tienen coma (,) como valor.mientras se realiza cualquier operación, SnapManager usa oracle.parameters.with.comma para comprobar todos los parámetros de Oracle y omitir la división de los valores.

Por ejemplo, si el valor de nls_numeric_characters=, especifique oracle.parameters.with.comma=nls_numeric_characters. Si hay varios parámetros de Oracle con coma como valor, debe especificar todos los parámetros en oracle.parameters.with.comma.



 a| 
* ArchivedLogs.Exclude
* ArchivedLogs.exclude.fileslike
* <db-unique-name>.archivedLogs.exclude.fileslike

 a| 
Estos parámetros permiten a SnapManager excluir los archivos de registro de archivado de los perfiles y las copias de seguridad si la base de datos no está en un sistema de almacenamiento habilitado para la copia snapshot y desea realizar operaciones SnapManager en ese sistema de almacenamiento.*Nota:* debe incluir los parámetros de exclusión en el archivo de configuración antes de crear un perfil.

Los valores asignados a estos parámetros pueden ser un directorio de nivel superior o un punto de montaje donde están presentes los archivos de registro de archivos o un subdirectorio.

Para excluir los archivos de registro de archivos de que se incluyan en el perfil y se realice una copia de seguridad, debe incluir uno de los parámetros siguientes:

* ArchivedLogs.exclude para especificar una expresión regular para excluir los archivos de registro de archivos de todos los perfiles o copias de seguridad.
+
Los archivos de registro de archivos que coinciden con la expresión regular se excluyen de todos los perfiles y copias de seguridad.

+
Por ejemplo, puede establecer archivedLogs.Exclude = J:\\ARCH\\.*.

+

NOTE: Si el destino tiene un separador de archivos, se debe agregar un símbolo de barra diagonal adicional (\) al patrón y éste debe terminar con un patrón de doble barra (\\.*).

* ArchivedLogs.exclude.filesLike de especificar una expresión SQL para excluir los archivos de registro de archivos de todos los perfiles o copias de seguridad.
+
Los archivos de registro de archivos que coinciden con la expresión SQL se excluyen de todos los perfiles y las copias de seguridad.

+
Por ejemplo, puede establecer archivedLogs.exclude.fileslike = J:\\ARCH2\\\%.

+

NOTE: Si el destino tiene un separador de archivos, se debe agregar un símbolo de barra diagonal adicional (\) al patrón y éste debe terminar con un patrón de doble barra (\\%).





 a| 
 a| 
* <db-unique-name>.ArchivedLogs.exclude.filesLike para especificar una expresión SQL para excluir los archivos de registro de archivos sólo del perfil o la copia de seguridad creada para la base de datos con el nombre-único-dB especificado.
+
Los archivos de registro de archivos que coinciden con la expresión SQL se excluyen del perfil y las copias de seguridad.

+
Por ejemplo, puede establecer mydB.archivedLogs.exclude.fileslike = J:\\ARCH2\\%.

+

NOTE: Si el destino tiene un separador de archivos, se debe agregar un símbolo de barra diagonal adicional (\) al patrón y éste debe terminar con un patrón de doble barra (\\%).



|===