---
permalink: windows/reference_the_smosmsaprepository_update_command.html 
sidebar: sidebar 
keywords: command, update, repository, database, profile, snapmanager, smo 
summary: Este comando actualiza el repositorio que almacena perfiles de base de datos y las credenciales asociadas al actualizar SnapManager. Cada vez que instale una nueva versión de SnapManager, debe ejecutar el comando de actualización del repositorio para poder utilizar la nueva versión. Puede utilizar este comando solo si no hay comandos incompletos en el repositorio. 
---
= El comando de actualización del almacén de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando actualiza el repositorio que almacena perfiles de base de datos y las credenciales asociadas al actualizar SnapManager. Cada vez que instale una nueva versión de SnapManager, debe ejecutar el comando de actualización del repositorio para poder utilizar la nueva versión. Puede utilizar este comando solo si no hay comandos incompletos en el repositorio.



== Sintaxis

[listing]
----

        smo repository update
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
[-force] [-noprompt]
\[-quiet \| -verbose\]
----


== Parámetros

* *-repositorio*
+
Las opciones que siguen a -repository especifican los detalles de la base de datos para el repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el repositorio. Utilice el nombre global o el SID.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *-login*
+
Inicia los detalles de inicio de sesión en el repositorio.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *-fuerza*
+
Intenta forzar la actualización del repositorio. SnapManager le solicita que realice una copia de seguridad del repositorio actual antes de la actualización.

* *-noprompt*
+
No muestra el mensaje antes de actualizar la base de datos del repositorio. El uso de la opción -noprompt garantiza que no aparezca la petición de datos, lo que facilita la actualización de repositorios mediante una secuencia de comandos.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el ejemplo siguiente se actualiza el repositorio de la base de datos SALESDB.

[listing]
----
smo repository update -repository -dbname SALESDB
-host server1 -login -username admin -port 1521
----