---
permalink: windows/reference_the_smo_notification_removesummarynotification_command.html 
sidebar: sidebar 
keywords: command, disable, summary, notification, multiple, profile, repository, database, smo, remove-summary-notification 
summary: Este comando deshabilita la notificación de resumen de varios perfiles en una base de datos de repositorio. 
---
= El comando remove-summary-notification de la notificación de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando deshabilita la notificación de resumen de varios perfiles en una base de datos de repositorio.



== Sintaxis

[listing]
----

        smo notification remove-summary-notification
-repository
-dbname repo_service_name
-port repo_port
-host repo_host
-login -username repo_username
\[-quiet \| -verbose\]
----


== Parámetros

* *-repositorio*
+
Las opciones que siguen a -repository especifican los detalles de la base de datos para el repositorio.

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el repositorio. Utilice el nombre global o el SID.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *-login repo_username*
+
Especifica el nombre de inicio de sesión necesario para acceder a la base de datos que almacena el repositorio.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.



En el siguiente ejemplo se deshabilita la notificación de resumen de varios perfiles en una base de datos de repositorio.

[listing]
----

smo notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login -username oba5
----