---
permalink: windows/reference_the_smosmsap_notification_updatesummarynotification_command.html 
sidebar: sidebar 
keywords: run, notification, update-summary-notification, command, enable, summary, repository, database, smo 
summary: Puede ejecutar el comando notification update-summary-notification para habilitar la notificación de resumen para una base de datos de repositorio. 
---
= El comando de notificación de actualización-resumen-notificación de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando notification update-summary-notification para habilitar la notificación de resumen para una base de datos de repositorio.



== Sintaxis

[listing]
----

        smo notification update-summary-notification
-repository
-port repo_port
-dbname  repo_service_name
-host repo_host
-login -username repo_username
-email email-address1,email-address2
-subject subject-pattern
-frequency
[-daily –time daily_time \|
-hourly –time hourly_time \|
-monthly –time monthly_time -date \[1\|2\|3\|...\|31\] \|
-weekly  –time weekly_time -day \[1\|2\|3\|4\|5\|6\|7\]\]
-profiles profile1,profile2
-notification-host notification-host
\[-quiet \| -verbose\]
----


== Parámetros

* *-repositorio*
+
Especifica los detalles de la base de datos del repositorio.

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos del repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos del repositorio. Es posible usar el nombre global o el identificador del sistema.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del host en el que reside la base de datos del repositorio.

* *-login*
+
Especifica los detalles de inicio de sesión del repositorio. Esto es opcional. Si no se especifica, SnapManager toma de forma predeterminada el modo de conexión de autenticación del sistema operativo.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos del repositorio.

* *-email-dirección1,e-mail-dirección2*
+
Especifica las direcciones de correo electrónico de los destinatarios.

* *-tema-patrón*
+
Especifica el patrón del asunto del correo electrónico.

* *-frequency { -daily --time daily_time | -time --time_time | -quannual --time mensual_time -date {1|2|3...|31 } | -semanal --time weekly_time -day {1|2|3|4|5|6|7 }*
+
Especifica el tipo de programación y la hora de la programación en el momento en que desea recibir la notificación por correo electrónico.

* *-profile1, profile2*
+
Especifica los nombres de perfil que requieren notificación por correo electrónico.

* *-notification-host-notification-host*
+
Especifica el host del servidor SnapManager desde el cual se envía el correo electrónico de notificación de resumen a los destinatarios. Puede proporcionar un nombre de host o una dirección IP para el host de notificación. También es posible actualizar la dirección IP del host o el nombre de host.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo

En el siguiente ejemplo se habilita la notificación de resumen para una base de datos de repositorio:

[listing]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1
----