---
permalink: windows/reference_the_smosmsapprofile_create_command.html 
sidebar: sidebar 
keywords: run, profile, create, command, database, repository, smo 
summary: Puede ejecutar el comando profile create para crear un perfil de una base de datos en un repositorio. Debe montar la base de datos antes de ejecutar este comando. 
---
= El comando smo profile create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando profile create para crear un perfil de una base de datos en un repositorio. Debe montar la base de datos antes de ejecutar este comando.



== Sintaxis

[listing]
----

        smo profile create
-profile profile
\[-profile-password profile_password\]
-repository
-dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database
-dbname db_dbname
-host db_host
[-sid  db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 ]
[-rman \{-controlfile \| \{-login
-username  rman_username -password  rman_password\}
-tnsname  rman_tnsname\}\}]


[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-pattern pattern
[]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
[-quiet | -verbose]
----


== Parámetros

* * perfil*
+
Especifica el nombre del perfil. Este nombre puede tener hasta 30 caracteres y debe ser único dentro del host.

* *-profile-password profile_password*
+
Especifique la contraseña del perfil.

* *-repositorio*
+
Las opciones que siguen -repository especifican los detalles de la base de datos que almacena el perfil.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *-sid db_sid*
+
Especifica el identificador del sistema de la base de datos que describe el perfil. De forma predeterminada, SnapManager utiliza el nombre de la base de datos como identificador del sistema. Si el identificador del sistema es diferente del nombre de la base de datos, debe especificarlo con la opción -sid.

* *-login*
+
Especifica los detalles de inicio de sesión del repositorio.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos del repositorio.

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos del repositorio.

* *-base de datos*
+
Especifica los detalles de la base de datos que describe el perfil. Esta es la base de datos que se realizará un backup, se restaurará o se clonará.

* *-dbname db_dbname*
+
Especifica el nombre de la base de datos que describe el perfil. Es posible usar el nombre global o el identificador del sistema.

* *-host db_host db_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos.

* *-login*
+
Especifica los detalles de inicio de sesión de la base de datos.

* *-username db_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que describe el perfil.

* *-password db_password*
+
Especifica la contraseña necesaria para acceder a la base de datos que describe el perfil.

* *-puerto db_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que describe el perfil.

* *-rman*
+
Especifica los detalles que utiliza SnapManager para catalogar los backups con Oracle Recovery Manager (RMAN).

* *-controllfile*
+
Especifica los archivos de control de la base de datos de destino en lugar de un catálogo como repositorio de RMAN.

* *-login*
+
Especifica los detalles de inicio de sesión de RMAN.

* *-password rman_password*
+
Especifica la contraseña que se utiliza para iniciar sesión en el catálogo de RMAN.

* *-username rman_username*
+
Especifica el nombre de usuario utilizado para iniciar sesión en el catálogo de RMAN.

* *-tnsname tnsname*
+
Especifica el nombre de conexión tnsname (que se define en el archivo tsname.ora).

* *-retener [-recuento n] [-duración m]] [-número n] [-duración m]] [-número n] [-duración m] [-número n] [-duración m]] [-mensual [-recuento n] [-duración m]]*
+
Especifica la política de retención para un backup donde se cuenta un número de retención o ambos, junto con una duración de retención para una clase de retención (por hora, día, semana, mes).

+
Para cada clase de retención, se puede especificar un recuento de retención o una duración de retención. La duración se encuentra en unidades de la clase (por ejemplo, horas por hora, días por día). Por ejemplo, si el usuario especifica solo una duración de retención de 7 para backups diarios, SnapManager no limitará la cantidad de backups diarios del perfil (ya que el número de retención es 0), pero SnapManager eliminará automáticamente los backups diarios creados hace más de 7 días.

* *-comentario*
+
Especifica el comentario de un perfil que describe el dominio del perfil.

* *-snapname-pattern patrón*
+
Especifica el patrón de nomenclatura para las copias Snapshot. También puede incluir texto personalizado, por ejemplo, HOPS para operaciones altamente disponibles, en todos los nombres de copias Snapshot. Puede cambiar el patrón de nomenclatura de las copias Snapshot al crear un perfil o después de crear el perfil. El patrón actualizado se aplica solo a las copias snapshot que aún no se han creado. Las copias Snapshot que existen conservan el patrón Snapname anterior. Puede utilizar varias variables en el texto del patrón.

* *-resumen-notificación*
+
Especifica que la notificación de resumen por correo electrónico está activada para el nuevo perfil.

* *-notification -success-email-mail_dirección1,dirección de correo electrónico.2 -subject_pattern*
+
Especifica que la notificación de correo electrónico está habilitada para el nuevo perfil de forma que los destinatarios reciban correos electrónicos cuando la operación de SnapManager se realice correctamente. Debe introducir una única dirección de correo electrónico o varias direcciones de correo electrónico a las que se enviarán las alertas por correo electrónico y un patrón de asunto del nuevo perfil.

+
También se puede incluir texto de asunto personalizado para el nuevo perfil. Puede cambiar el texto del asunto cuando cree un perfil o después de que se haya creado el perfil. El asunto actualizado sólo se aplica a los correos electrónicos que no se envían. Puede usar varias variables para el asunto del correo electrónico.

* *-notification -failure -email correo-e_dirección1,dirección de correo-e-dirección2 -subject_pattern*
+
Especifica que la habilitación de la notificación por correo electrónico está habilitada para el nuevo perfil, de modo que los destinatarios reciban los correos electrónicos cuando falle la operación de SnapManager. Debe introducir una única dirección de correo electrónico o varias direcciones de correo electrónico a las que se enviarán las alertas por correo electrónico y un patrón de asunto del nuevo perfil.

+
También se puede incluir texto de asunto personalizado para el nuevo perfil. Puede cambiar el texto del asunto cuando cree un perfil o después de que se haya creado el perfil. El asunto actualizado sólo se aplica a los correos electrónicos que no se envían. Puede usar varias variables para el asunto del correo electrónico.

* *-separate-archivvelog-backups*
+
Especifica que el backup de registros de archivos está separado del backup del archivo de datos. Este es un parámetro opcional que puede proporcionar al crear el perfil. Después de separar el backup con esta opción, es posible tomar el backup solo de los archivos de datos o el backup de solo los registros de archivos.

* *-retain-archivvelog-backups -horas | -daysdays | -weeksweeks| -months*
+
Especifica que los backups de los registros de archivos se retendrán según la duración de la retención del registro de archivos (hora, día, semana, mensual).

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.

* *-include-with-online-backups*
+
Especifica que el backup de registros de archivos se incluye junto con el backup de la base de datos en línea.

* *-no-include-with-online-backups*
+
Especifica que no se incluyen los backups de registros de archivos junto con el backup de la base de datos en línea.

* *-dump*
+
Especifica que los archivos de volcado se recopilan después de la operación de creación de perfiles correcta.





== Ejemplo

El siguiente ejemplo muestra la creación de un perfil con una política de retención de horas y notificaciones por correo electrónico:

[listing]
----
smo profile create -profile test_rbac -profile-password netapp -repository -dbname SMOREP -host hostname.org.com -port 1521 -login -username smorep -database -dbname
RACB -host saal -sid racb1 -login -username sys -password netapp -port 1521 -rman -controlfile -retain -hourly -count 30 -verbose
Operation Id [8abc01ec0e78ebda010e78ebe6a40005] succeeded.
----
*Información relacionada*

xref:concept_managing_profiles_for_efficient_backups.adoc[Gestionar perfiles para backups eficientes]

xref:concept_snapshot_copy_naming.adoc[Nomenclatura de copias Snapshot]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[Cómo SnapManager retiene los backups en el almacenamiento local]
