---
permalink: windows/task_creating_repositories.html 
sidebar: sidebar 
keywords: snapmanager, require, repository, host, hold, data, operation, perform, creating, repositories 
summary: SnapManager requiere un repositorio en un host para conservar datos acerca de las operaciones que se realizan. 
---
= Creación de repositorios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager requiere un repositorio en un host para conservar datos acerca de las operaciones que se realizan.

Asegúrese de que se han completado las siguientes tareas:

. Cree un usuario y una contraseña de Oracle en la base de datos del repositorio.
. Autorizar el acceso de los usuarios al repositorio.


Para un repositorio, SnapManager para Oracle requiere un tamaño de bloque mínimo de 4K para el espacio de tablas en el que está instalado. Puede comprobar el tamaño de bloque con el siguiente comando de SQL:

[listing]
----
select a.username, a.default_tablespace, b.block_size
from dba_users a, dba_tablespaces b
a.username = repo_user
----
donde

* a.default_tablespace = b.tablespace_name
* a.username = el nombre de usuario en el repositorio


Si va a actualizar repositorios, debe reiniciar el servidor SnapManager para reiniciar todas las programaciones asociadas.

. Para crear el repositorio, introduzca el comando create repository, utilizando el siguiente formato general: smo Repository create -repository -dbname repo_service_name -host repo_host -login -username repo_username -Port repo_Port-force] [-noprompt] [-quiet | -verbose]
+
Donde:

+
** -repository -dbname es el nombre de la base de datos del repositorio.
** -host es el nombre del host para el repositorio.
** -username es el nombre del usuario de la base de datos que tiene acceso al repositorio.
** -port es el puerto para el host. Las demás opciones para este comando son las siguientes:


+
[-force] [-noprompt]

+
+

+
+ NOTA: Si tiene un repositorio existente con el mismo nombre y utiliza la opción -force , se sobrescribirán todos los datos de un esquema de repositorio existente.





== Crear un repositorio

La siguiente línea de comandos crea un repositorio.

[listing]
----
smo repository create -repository -dbname HRDP
-host server1 -login -username admin -port 1521
----