---
permalink: windows/task_order_of_performing_operations.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, operation, backup, cloning, clone, operation, order, perform 
summary: SnapManager le permite realizar diversas operaciones, como la creación de perfiles, la realización de backups y la clonado de backups. Estas operaciones deben realizarse en un orden específico. 
---
= Orden de realización de operaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager le permite realizar diversas operaciones, como la creación de perfiles, la realización de backups y la clonado de backups. Estas operaciones deben realizarse en un orden específico.

. Crear un perfil en un almacén existente mediante el comando smo profile create.
+

NOTE: El usuario de Oracle especificado para la base de datos de destino debe tener privilegios de sysdba.

+
En el siguiente ejemplo se muestra el comando para crear un perfil:

+
[listing]
----
smo profile create -profile prof1 -profile-password prof1cred
-repository -dbname HR1 -login -username admin -host server1 -port 1521
-database -dbname dedb -login -username db_oper2
-password dbpw1 -host server1 -port 1521
----
. Crear un backup en un perfil existente con el comando smo backup create.
+
En el ejemplo siguiente se muestra el comando para crear un backup:

+
[listing]
----
smo backup create -profile prof1 -full -offline -label full_backup_prof1 -force
----
. Restaurar y recuperar un backup de base de datos en el almacenamiento primario mediante el comando smo backup restore.
+
El ejemplo siguiente muestra el comando para restaurar un backup:

+
[listing]
----
smo backup restore -profile prof1 -label full_backup_prof1
-complete -recover -alllogs
----
. Crear una especificación de clon con el comando de plantilla de clon de smo.
+
Puede utilizar el asistente Clone de la interfaz gráfica de usuario (GUI) para crear una especificación del clon de plantilla. También puede crear el archivo de especificación del clon mediante un editor de texto.

. Clonar una base de datos con un backup existente mediante el comando smo clone create.
+
Debe tener una especificación de clon existente o crear una especificación de clon para especificar las especificaciones de almacenamiento y base de datos del clon.

+
En el ejemplo siguiente se muestra el comando para crear un clon:

+
[listing]
----
smo clone create -profile prof1 -backup-label full_backup_prof1
-newsid clone1 -label prof1_clone -clonespec C:\\clone_spec\\prof1_clonespec.xml
----

