---
permalink: windows/task_configuring_e_mail_notification_for_a_new_profile.html 
sidebar: sidebar 
keywords: creating, new, profile, configure, email, notification, completion, database, operation, configuring 
summary: Cuando se crea un perfil nuevo, se puede configurar para recibir una notificación por correo electrónico al finalizar la operación de la base de datos. 
---
= Configuración de la notificación por correo electrónico para un perfil nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se crea un perfil nuevo, se puede configurar para recibir una notificación por correo electrónico al finalizar la operación de la base de datos.

* Debe configurar la dirección de correo electrónico desde la cual se envían las alertas.
* Debe usar una lista separada por comas para varias direcciones de correo electrónico.
+
Debe asegurarse de que no hay espacio entre la coma y la siguiente dirección de correo electrónico.

+

NOTE: Asegúrese de introducir el conjunto de direcciones de correo electrónico entre comillas dobles.

+
.. Introduzca el siguiente comando: smo profile create -profileprofile [-profile-passwordprofile_password] -repository [-dbnamercompenso_service_name-hotpo_host-portrepo_Port-login-usernamerepo] [-nombre-nombre-usuario_base-dbnamedb] [-nombre_nombre_usuario]-nombredeusuario_archivo] [-nombredeusuario_archivo-did]-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario] [-nombredeusuario-nombredearchivo-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario] [-nombredeusuario-nombredeusuario]-nombredeusuario]-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario] [-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario] [-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario] [-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario] [-archivo
+
Las demás opciones para este comando son las siguientes:

+
[-fuerza]

+

NOTE: SnapManager admite hasta 1000 caracteres para las direcciones de correo electrónico.

+
Cuando se crea un backup de archivos de datos y archivos de registro de archivos junto con el perfil (para crear backups de registros de archivos independientes) y se produce un error en la creación del backup de archivos de datos, la notificación por correo electrónico se envía con el backup de datos como nombre de la operación en lugar de un backup de datos y un backup de registros de archivos. Cuando la operación de backup de archivo de datos y archivo de registro de archivo se realiza correctamente, se muestra el resultado de la siguiente manera:

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----



