---
permalink: windows/task_adding_existing_profile_to_summary_notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, exist, profile, summary, email, notification, updating 
summary: SnapManager le permite añadir un perfil existente a una notificación de correo electrónico de resumen al actualizar dicho perfil. 
---
= Adición de un perfil existente para resumir las notificaciones por correo electrónico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager le permite añadir un perfil existente a una notificación de correo electrónico de resumen al actualizar dicho perfil.

. Introduzca el siguiente comando: smo profile update -profileprofile_name [-profile-passwordprofile_password] -reposisero_service_name-hostrepo_host-portrepo_Port-login-ususernamerepo [-nombre_base-dbedb_dbedb_nombre_nombre_hostDB]-nombre_host [-nombre_did_usuario_did]-did]-disermb]-nombre_usuariob]-nombre_nombre_nombre_nombre_usuariob] [-nombre_nombre_nombre_nombre_nombre_nombre_nombre_usuario]-nombre_nombre_nombre_usuario]-nombre_d]-nombre_usuariob]-nombre_usuariob]-nombre_usuariob]-nombre_nombre_nombre_nombre_nombre_d]-nombre_nombre_nombre_nombre_usuariob] [-usuariob] [-nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_usuario]-nombre_nombre_nombre_d]-nombre_nombre_d]-usuariob]-

