---
permalink: windows/task_mounting_backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, oracle, recovery, manager, rman 
summary: 'SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También es posible montar backups en situaciones en las que se utilice una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad.' 
---
= Montar backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También es posible montar backups en situaciones en las que se utilice una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad.

Si utiliza RMAN, debe utilizar la operación de montaje para cambiar el estado de un backup (que permite el acceso) y la operación de desmontaje para cambiar el estado de un backup (que quita el acceso).

El comando smo backup Mount muestra una lista de rutas donde se han montado las copias Snapshot consistentes en el backup.


NOTE: Opcionalmente, es posible recoger los archivos de volcado después de una operación de montaje de backup exitosa o con errores.

. Para montar una copia de seguridad, introduzca el siguiente comando: smo backup Mount -profile profile_name {labellabel [data | -archivvelogs] | -idid} [-host-dump] [-quiet | -verbose]


*Información relacionada*

xref:reference_the_smosmsapbackup_mount_command.adoc[El comando de montaje de backup de smo]
