---
permalink: windows/task_freeing_backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, fuction, space, smo 
summary: Es posible liberar backups, lo que elimina las copias Snapshot sin eliminar los metadatos de los backups. Esta función libera el espacio ocupado por la copia de seguridad. Puede utilizar el comando libre del backup de smo para liberar los backups. 
---
= Liberando backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible liberar backups, lo que elimina las copias Snapshot sin eliminar los metadatos de los backups. Esta función libera el espacio ocupado por la copia de seguridad. Puede utilizar el comando libre del backup de smo para liberar los backups.

Para que un backup pueda ser apto para liberar, debe asegurarse de lo siguiente:

* La copia de seguridad se ha realizado correctamente
* La copia de seguridad no se va a montar
* El backup no tiene clones
* El backup no se conservará mediante una política de retención ilimitada
* El backup no se ha liberado todavía


Es posible especificar la opción -dump como un parámetro opcional para recoger los archivos de volcado después de la operación de backup libre exitosa o con errores.

. Introduzca el siguiente comando: smo backup free -profileprofile_name {-labellabel [data | -archivvelogs] | -idid | -all} -force [-dump] [-quiet] [-force]


*Información relacionada*

xref:reference_the_smosmsapbackup_free_command.adoc[El comando libre de backup de smo]
