---
permalink: unix-administration/concept_general_layout_and_configuration.html 
sidebar: sidebar 
keywords: recommend, general, database, layout, storage, configuration, avoid, issue, disk, group, file, lun 
summary: Conocer los diseños generales recomendados de las bases de datos y las configuraciones de almacenamiento puede ayudarle a evitar problemas relacionados con los grupos de discos, los tipos de archivos y los espacios de tablas. 
---
= Diseños generales de bases de datos y configuraciones de almacenamiento recomendados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conocer los diseños generales recomendados de las bases de datos y las configuraciones de almacenamiento puede ayudarle a evitar problemas relacionados con los grupos de discos, los tipos de archivos y los espacios de tablas.

* No incluya archivos de más de un tipo de sistema de archivos SAN o administrador de volúmenes en la base de datos.
+
Todos los archivos que conforman una base de datos deben residir en el mismo tipo de sistema de archivos.

* SnapManager requiere un gran tamaño de bloque de 4 KB.
* Incluyen el identificador del sistema de la base de datos en el archivo oratab.
+
Incluir una entrada en el archivo oratab de cada base de datos que se gestionará. SnapManager utiliza el archivo oratab para determinar qué directorio raíz de Oracle usar.

* Para registrar backups de SnapManager en Oracle RMAN, debe crear perfiles habilitados para RMAN.


Si desea aprovechar la nueva restauración basada en volúmenes o la restauración de grupos de discos completos, tenga en cuenta las siguientes directrices relacionadas con los sistemas de archivos y los grupos de discos:

* Varias bases de datos no pueden compartir el mismo grupo de discos de Automatic Storage Management (ASM).
* Un grupo de discos que contiene archivos de datos no puede contener otros tipos de archivos.
* El número de unidad lógica (LUN) para el grupo de discos de archivos de datos debe ser el único objeto del volumen de almacenamiento.


A continuación se muestran algunas directrices para la separación de volúmenes:

* Los archivos de datos de una sola base de datos deben estar en el volumen.
* Debe utilizar volúmenes independientes para cada una de las siguientes clasificaciones de archivos: Archivos binarios de base de datos, archivos de datos, archivos redo log en línea, archivos redo log archivados y archivos de control.
* No es necesario crear un volumen separado para los archivos de base de datos temporales, ya que SnapManager no realiza backups de archivos de base de datos temporales.

