---
permalink: unix-administration/concept_snapmanger_limitations_for_clustered_data_ontap.html 
sidebar: sidebar 
keywords: limitations, functionalities, snapmanager, operations, ontap, cluster, data 
summary: Debe conocer las limitaciones de algunas funcionalidades y operaciones de SnapManager si utiliza Clustered Data ONTAP. 
---
= Limitaciones de SnapManager para Clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer las limitaciones de algunas funcionalidades y operaciones de SnapManager si utiliza Clustered Data ONTAP.

Las siguientes funcionalidades no son compatibles si utiliza SnapManager en Clustered Data ONTAP:

* Funcionalidades de protección de datos si SnapManager se integra con Unified Manager de OnCommand
* Una base de datos en la que una LUN pertenece a un sistema que ejecuta Data ONTAP en 7-Mode y la otra LUN pertenece a un sistema que ejecuta Clustered Data ONTAP
* SnapManager para Oracle no admite la migración de un Vserver, que no es compatible con Clustered Data ONTAP
* SnapManager para Oracle no admite la funcionalidad Clustered Data ONTAP 8.2.1 para especificar diferentes políticas de exportación para volúmenes y qtrees

