---
permalink: unix-administration/concept_restore_process_identification.html 
sidebar: sidebar 
keywords: restore, process, support, snapmanager, oracle, file-based, backup 
summary: Todas las versiones de SnapManager para Oracle no admiten todos los procesos de restauración. Después de actualizar SnapManager, debe tener en cuenta el proceso de restauración que puede usar para restaurar un backup. 
---
= Restaurar tipos de proceso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Todas las versiones de SnapManager para Oracle no admiten todos los procesos de restauración. Después de actualizar SnapManager, debe tener en cuenta el proceso de restauración que puede usar para restaurar un backup.

Los backups creados con SnapManager 3.0 o versiones posteriores pueden restaurarse utilizando procesos rápidos de restauración y restauración basada en archivos. Sin embargo, los backups creados con una versión anterior a SnapManager 3.0 se pueden restaurar utilizando únicamente el proceso de restauración basada en archivos.

Puede determinar la versión de SnapManager utilizada para crear el backup mediante la ejecución del comando -backup show.

*Información relacionada*

xref:concept_what_database_restore_is.adoc[Qué es la restauración de base de datos]
