---
permalink: unix-administration/concept_limitations_related_to_oracle_database.html 
sidebar: sidebar 
keywords: snapmanager, limitations, oracle, database, 10gr2, 11gr1, 11gr2, 12_c_, ocds, dnfs 
summary: Antes de empezar a trabajar con SnapManager, debe conocer las limitaciones relacionadas con la base de datos de Oracle. 
---
= Limitaciones relacionadas con Oracle Database
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de empezar a trabajar con SnapManager, debe conocer las limitaciones relacionadas con la base de datos de Oracle.

Estas limitaciones son las siguientes:

* SnapManager es compatible con las versiones 10gR2, 11gR1, 11gR2 y 12__c___, pero no es compatible con Oracle 10gR1 como repositorio o base de datos de destino.
* SnapManager no admite el uso de una dirección IP DE EXPLORACIÓN en lugar de un nombre de host.
+
SCAN IP es una nueva función de Oracle 11gR2.

* SnapManager no es compatible con Oracle Cluster File System (OCFS).
* Oracle 11g en un entorno de NFS directo (dNFS) permite configuraciones de punto de montaje adicionales en el archivo Naranfstab, como varias rutas para el equilibrio de carga.
+
SnapManager no modifica el archivo anorfstab. Debe agregar manualmente todas las propiedades adicionales que desee que utilice la base de datos clonada en el archivo oranfstab.

* La compatibilidad con bases de datos Oracle 9i se usa en SnapManager 3.2.
* La compatibilidad con la base de datos Oracle 10gR2 (anterior a 10.2.0.5) queda obsoleta en SnapManager 3.3.1.



NOTE: Identifique las distintas versiones de las bases de datos de Oracle que se admiten en la matriz de interoperabilidad.

*Información relacionada*

http://support.netapp.com/NOW/products/interoperability/["Matriz de interoperabilidad: support.netapp.com/NOW/products/interoperability"]
