---
permalink: unix-administration/concept_restoring_database_backup.html 
sidebar: sidebar 
keywords: snapmanager, oracle, restore, database, snapshot, file-based, backup, scn, local 
summary: 'SnapManager para Oracle le permite restaurar una base de datos al estado que tenía cuando se tomó una copia Snapshot. Además del proceso de restauración basada en archivos, SnapManager admite la tecnología de restauración rápida basada en volúmenes, lo que reduce el tiempo de restauración de forma significativa en comparación con otros métodos de recuperación. Debido a que los backups se crean con más frecuencia, se reduce el número de registros que se debe aplicar, lo que reduce el tiempo medio de recuperación (MTTR) de una base de datos.' 
---
= Restaurar backups de base de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager para Oracle le permite restaurar una base de datos al estado que tenía cuando se tomó una copia Snapshot. Además del proceso de restauración basada en archivos, SnapManager admite la tecnología de restauración rápida basada en volúmenes, lo que reduce el tiempo de restauración de forma significativa en comparación con otros métodos de recuperación. Debido a que los backups se crean con más frecuencia, se reduce el número de registros que se debe aplicar, lo que reduce el tiempo medio de recuperación (MTTR) de una base de datos.

A continuación, se muestran algunas de las tareas que se pueden realizar en relación con la restauración y la recuperación de datos en bases de datos:

* Realizar una restauración basada en archivos o una restauración basada en volúmenes, que es el método más rápido de restaurar backups de base de datos y es el valor predeterminado que utiliza SnapManager.
* Restaure todo el backup o parte del mismo.
+
Cuando se restaura una parte de la misma, se especifica un grupo de espacios de tablas o un grupo de archivos de datos. También puede restaurar los archivos de control junto con los datos o solo los propios archivos de control.

* Recupere los datos en función de un momento específico o de todos los registros disponibles, que almacena la última transacción comprometida con la base de datos.
+
El punto en el tiempo puede ser un número de cambio de sistema (SCN) de Oracle o una fecha y hora (aaaa-mm-dd:hh:mm:ss). SnapManager utiliza el reloj de 24 horas.

* Restauración desde backups en el almacenamiento principal (backups locales).
* Restaurar y recuperar la copia de seguridad mediante SnapManager, o usar SnapManager para restaurar la copia de seguridad y utilizar otra herramienta, como Recovery Manager (RMAN), para recuperar los datos.
* Restaurar backups desde ubicaciones alternativas.
* Restaure los backups protegidos del almacenamiento secundario (backups remotos) y desde una ubicación alternativa mediante el archivo de especificación de restauración.


Puede restaurar una copia de seguridad realizada por una versión anterior de SnapManager utilizando SnapManager 3.0 y versiones posteriores.

SnapManager también permite restaurar las bases de datos de gestión automática de almacenamiento (ASM). Un grupo de discos ASM puede compartirse con varias bases de datos. Por lo tanto, no es posible revertir a una copia Snapshot más antigua del grupo de discos, ya que revería todas las bases de datos. Las soluciones tradicionales de operaciones de restauración pasan por el host y requieren que todos los bloques que conforman la base de datos se muevan del sistema de almacenamiento al host y, después, al sistema de almacenamiento. SnapManager libera esta sobrecarga, ya que permite restaurar solo los datos necesarios en el grupo de discos de ASM sin pasar por el host.

Los administradores pueden realizar operaciones de restauración o recuperación mediante la interfaz gráfica de usuario (GUI) de SnapManager o mediante la interfaz de línea de comandos (CLI).

*Información relacionada*

xref:concept_database_backup_management.adoc[Realizar backups de bases de datos]

xref:reference_the_smosmsapbackup_restore_command.adoc[El comando smo backup restore]
