---
permalink: unix-administration/concept_how_to_collect_dump_files.html 
sidebar: sidebar 
keywords: -dump, snapmanager, command, collect, dump, file, successful, fail, creating, updating, verify 
summary: Es posible incluir -dump en el comando SnapManager para recoger los archivos de volcado después de una operación de SnapManager correcta o con errores. 
---
= Cómo recopilar archivos de volcado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible incluir -dump en el comando SnapManager para recoger los archivos de volcado después de una operación de SnapManager correcta o con errores.

Es posible recoger archivos de volcado para las siguientes operaciones de SnapManager:

* Creación de perfiles
* Actualizando perfiles
* Crear backups
* Verificación de backups
* Eliminar backups
* Liberando backups
* Montar backups
* Desmontaje de backups
* Restaurar backups
* Crear clones
* Eliminar clones
* Dividir clones



NOTE: Al crear un perfil, puede recopilar archivos de volcado sólo si la operación se realiza correctamente. Si se produce un error al crear un perfil, debe utilizar el comando de volcado del sistema smsystem. Para que los perfiles se realicen correctamente, puede utilizar los comandos de volcado smooperation y smoprofile para recopilar los archivos de volcado.

*ejemplo*

[listing]
----

      smo  backup create -profile targetdb1_prof1 -auto -full -online -dump
----