---
permalink: unix-administration/concept_what_cloning_is.html 
sidebar: sidebar 
keywords: clone, database, replica, original, database, clone, full, backup, current, system, dlexclone, snapmanager 
summary: Puede clonar una base de datos para crear una réplica exacta de la base de datos original. Es posible crear el clon a partir de un backup completo o desde el estado actual de la base de datos. 
---
= Qué es la clonación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede clonar una base de datos para crear una réplica exacta de la base de datos original. Es posible crear el clon a partir de un backup completo o desde el estado actual de la base de datos.

A continuación se presentan algunas de las ventajas de crear un clon con SnapManager:

|===
| Ventajas | Detalles 


 a| 
Velocidad
 a| 
La operación de clonación de SnapManager usa la función FlexClone disponible con Data ONTAP. Esto permite clonar rápidamente grandes volúmenes de datos.



 a| 
Gestión eficiente del espacio
 a| 
Cuando crea un clon con SnapManager, solo se necesita espacio para los cambios entre el backup y el clon. Un clon SnapManager es una copia Snapshot editable de la base de datos original y puede crecer según sea necesario. Por el contrario, un clon físico de la base de datos requiere que disponga de espacio suficiente para copiar la base de datos completa.



 a| 
Copia virtual
 a| 
Puede utilizar la base de datos clonada como si fuera la base de datos original. Por ejemplo, puede usar un clon para pruebas, comprobaciones de plataformas y actualizaciones, simulaciones múltiples aplicadas a un conjunto de datos de gran tamaño, y pruebas y almacenamiento provisional en oficinas remotas. Los cambios en el clon no afectan a la base de datos original. Una vez clonada la base, la base de datos clonada queda totalmente operativa.



 a| 
Sencillez
 a| 
Es posible clonar una base de datos a cualquier host con los comandos de SnapManager.

|===
Es posible clonar un backup en el almacenamiento primario (local) o un backup protegido que está en el almacenamiento secundario (remoto). Sin embargo, no es posible clonar un backup si la operación de backup está en curso o si el backup se transfirió al almacenamiento secundario.

Para poder clonar una base de datos, debe asegurarse de que se cumplen los siguientes requisitos previos:

* Asegúrese de que el directorio [/etc|/var/opt/oracle]/oratab no contenga una entrada que apunte al identificador del sistema de destino.
* Elimine el archivo speLATRY <SID>.ora de $ORACLE_HOME/DBS.
* Elimine el archivo <SID>.ora de $ORACLE_HOME/DBS.
* Elimine los destinos de volcado de Oracle que estén especificados en el archivo de especificación del clon.
* Elimine los archivos de control de Oracle que estén especificados en el archivo de especificación del clon.
* Elimine los archivos de registro de recuperación de Oracle especificados en el archivo de especificación del clon.


Debe proporcionar al clon un nuevo identificador del sistema. No se pueden ejecutar simultáneamente dos bases de datos con el mismo identificador de sistema en el mismo host. Es posible tener un clon en otro host con el mismo identificador de sistema. Es posible asignar al clon una etiqueta o dejar que SnapManager cree una etiqueta con el identificador del sistema, la fecha y la hora en que se creó el clon.

Cuando introduce una etiqueta, no debe incluir espacios ni caracteres especiales.

Como parte del proceso de clonado, SnapManager crea los parámetros y archivos de Oracle necesarios para la base de datos clonada. Un ejemplo de un archivo de Oracle necesario es el archivo <SID>.ora de Re.

Cuando se clona una base de datos, SnapManager crea un nuevo archivo <SID>.ora para la base de datos en el directorio $ORACLE_HOME/DBS.

Cuando SnapManager clona el almacenamiento de una base de datos, también crea un nuevo punto de montaje del sistema de archivos, pero no cambia la estructura de directorio en el punto de montaje desde la CLI de SnapManager. No obstante, desde la interfaz gráfica de usuario de SnapManager, es posible cambiar la estructura de directorio y los metadatos del sistema de archivos.

Oracle 11g en un entorno de NFS directo (DNFS) permite una configuración de punto de montaje adicional, como varias rutas para el equilibrio de carga en el archivo Naranfstab. SnapManager no modifica este archivo, por lo que cualquier propiedad adicional que desee que utilice un clon debe agregarse manualmente al archivo oranfstab después de realizar la clonación con SnapManager.

Puede clonar una base de datos de Real Application Cluster (RAC) y una base de datos no cluster. Un clon de RAC se inicia como una sola base de datos.

Es posible clonar un backup de base de datos en el host en el que reside la base de datos o en un host alternativo.

También es posible clonar una base de datos ASM en un host remoto. Cuando lo haga, debe asegurarse de que la instancia de ASM esté en ejecución en el host remoto.

Si la base de datos clonada utilizaba un archivo spfile, SnapManager crea un archivo spfile para el clon. Coloca este archivo en el directorio $ORACLE_HOME/DBS y crea la estructura de directorios para los archivos de diagnóstico. el nombre de archivo es spfile <SID>.ora.
