---
permalink: unix-administration/reference_the_smosmsap_clone_split_command.html 
sidebar: sidebar 
keywords: clone, split, command, independent, original, snapmanager 
summary: Puede ejecutar el comando clone split para dividir un clon. El clon de división se independiza del clon original. SnapManager genera un nuevo perfil después de la operación de división de clones y se puede usar este perfil para gestionar el clon dividido. 
---
= El comando de división de clones de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando clone split para dividir un clon. El clon de división se independiza del clon original. SnapManager genera un nuevo perfil después de la operación de división de clones y se puede usar este perfil para gestionar el clon dividido.



== Sintaxis

[listing]
----

        smo clone split
-profile clone-profile
\[-host hostname\]
\{-label clone-label | -id clone-id\} \[-split-label split-operation_label\]
\[-comment comment\]
-new-profile new-profile-name \[-profile-password new-profile_password\]
-repository -dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database -dbname db_dbname
-host db_host \[-sid db_sid\] \[-login -username db_username -password db_password
-port db_port\]
\[-rman \{\{-controlfile \| \{-login -username rman_username
-password rman_password\} -tnsname rman_tnsname\}\}\]
-osaccount osaccount
-osgroup osgroup
\[-retain
\[-hourly \[-count n\] \[-duration  m\]\]
\[-daily \[-count n\] \[-duration m\]\]
\[-weekly  \[-count n\] \[-duration m\]\]
\[-monthly \[-count n\] \[-duration m\]\] \]
\[-profile-comment profile-comment\]
\[-snapname-pattern pattern\]
\[-protect \[-protection-policy policy_name\]\] \| \[-noprotect\]\]
\[-summary-notification
\[-notification
\[-success -email email_address1,email_address2
-subject subject-pattern\]
\[failure -email email_address1,email_address2
-subject subject-pattern\] \]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name \| -noprotect]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== Parámetros

* *-perfil clone-profile*
+
Especifica el nombre del perfil a partir del cual se crea el clon.

* *-host hostname*
+
Especifica el nombre de host en el que existe el clon.

* *-etiqueta clon-etiqueta*
+
Especifica el nombre de etiqueta generado por la operación de clonado.

* *-id clone-id*
+
Especifica el ID único generado por la operación de clonado.

* *-split-label split-operation_label*
+
Especifica el nombre de etiqueta generado por la operación de clonado.

* *-new-profile new-profile_name*
+
Especifica el nuevo nombre de perfil que generará SnapManager después de una operación de división correcta.

* *-profile-password new-profile_password*
+
Especifica la contraseña del perfil.

* *-repositorio*
+
Especifica los detalles de la base de datos para el repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el repositorio. Es posible usar el nombre global o el identificador del sistema.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que reside la base de datos del repositorio.

* *-port repo_port*
+
Especifica el número de puerto del protocolo de control de transmisión (TCP) que se utiliza para acceder al host en el que reside la base de datos del repositorio.

* *-login*
+
Especifica los detalles de inicio de sesión del repositorio. Esto es opcional. Si no se especifica, SnapManager toma de forma predeterminada el modo de conexión de autenticación del sistema operativo.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder al host en el que reside la base de datos del repositorio.

* *-base de datos*
+
Especifica los detalles de la base de datos que se realizará un backup, se restaurará o se clonará.

* *-dbname db_dbname*
+
Especifica el nombre de la base de datos que describe el perfil. Es posible usar el nombre global o el identificador del sistema.

* *-host db_host*
+
Especifica el nombre o la dirección IP del equipo host en el que reside la base de datos.

* *-sid db_sid*
+
Especifica el identificador del sistema de la base de datos que describe el perfil. De forma predeterminada, SnapManager utiliza el nombre de la base de datos como identificador del sistema. Si el identificador del sistema es diferente del nombre de la base de datos, debe especificarlo mediante la opción -sid.

+
Por ejemplo, si utiliza Real Application Clusters (RAC) de Oracle, debe especificar el identificador del sistema de la instancia de RAC en el nodo de RAC desde el cual se ejecuta SnapManager.

* *-login*
+
Especifica los detalles de inicio de sesión de la base de datos.

* *-username db_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que describe el perfil.

* *-password db_password*
+
Especifica la contraseña necesaria para acceder a la base de datos que describe el perfil.

* *-rman*
+
Especifica los detalles que utiliza SnapManager para catalogar los backups con Oracle Recovery Manager (RMAN).

* *-controllfile*
+
Especifica los archivos de control de la base de datos de destino como repositorio de RMAN en lugar de como catálogo.

* *-login*
+
Especifica los detalles de inicio de sesión de RMAN.

* *-password rman_password*
+
Especifica la contraseña que se utiliza para iniciar sesión en el catálogo de RMAN.

* *-username rman_username*
+
Especifica el nombre de usuario utilizado para iniciar sesión en el catálogo de RMAN.

* *-tnsname tnsname*
+
Especifica el nombre de conexión tnsname (que se define en el archivo tsname.ora).

* *-osaccount*
+
Especifica el nombre de la cuenta de usuario de la base de datos Oracle. SnapManager utiliza esta cuenta para realizar operaciones de Oracle como el inicio y el apagado. Generalmente, es el usuario propietario del software de Oracle en el host, por ejemplo, oracle.

* *-osgroup osgroup*
+
Especifica el nombre del grupo de base de datos Oracle asociado a la cuenta de oracle.

+

NOTE: Las variables -osaccount y -osgroup son necesarias para UNIX, pero no se permiten para bases de datos que se ejecutan en Windows.

* *-retener [-recuento n] [-duración m]] [-número n] [-duración m]] [-número n] [-duración m] [-número n] [-duración m]] [-mensual [-recuento n] [-duración m]]*
+
Especifica la política de retención para un backup.

+
Para cada clase de retención, se puede especificar el recuento de retención o la duración de la retención, o bien tanto. La duración se encuentra en unidades de la clase (por ejemplo, horas por hora, días por día). Por ejemplo, si especifica solo una duración de retención de 7 para backups diarios, SnapManager no limitará la cantidad de backups diarios del perfil (ya que el número de retención es 0), pero SnapManager eliminará automáticamente los backups diarios creados hace más de 7 días.

* *-perfil-comentario perfil-comentario*
+
Especifica el comentario de un perfil que describe el dominio del perfil.

* *-snapname-pattern patrón*
+
Especifica el patrón de nomenclatura para las copias Snapshot. También puede incluir texto personalizado, por ejemplo, HOPS para operaciones altamente disponibles, en todos los nombres de copias Snapshot. Puede cambiar el patrón de nomenclatura de las copias Snapshot al crear un perfil o después de crear el perfil. El patrón actualizado se aplica solo a las copias snapshot que aún no se han creado. Las copias Snapshot que existen conservan el patrón Snapname anterior. Puede utilizar varias variables en el texto del patrón.

* *-protect -protection-policy policy_name*
+
Especifica si el backup debe protegerse en el almacenamiento secundario.

+

NOTE: Si -Protect se especifica sin -protection-policy, el conjunto de datos no tendrá una política de protección. Si se especifica -Protect y la política de protección no se establece cuando se crea el perfil, puede establecerlo más adelante mediante el comando de actualización de perfil de smo o el administrador de almacenamiento lo establece mediante la consola de Protection Manager.

* *-resumen-notificación*
+
Especifica los detalles para configurar la notificación de resumen por correo electrónico para varios perfiles en una base de datos de repositorio. SnapManager genera este correo electrónico.

* *-notificación*
+
Especifica los detalles para configurar la notificación por correo electrónico para el nuevo perfil. SnapManager genera este correo electrónico. La notificación por correo electrónico permite al administrador de la base de datos recibir correos electrónicos sobre el estado correcto o con errores de la operación de base de datos que se realiza mediante este perfil.

* *-éxito*
+
Especifica que la notificación de correo electrónico está habilitada para un perfil para cuando la operación de SnapManager se realiza correctamente.

* *-dirección de correo electrónico 1 dirección de correo electrónico 2*
+
Especifica la dirección de correo electrónico del destinatario.

* *-tema-patrón*
+
Especifica el asunto del correo electrónico.

* *-fallo*
+
Especifica que la notificación por correo electrónico está habilitada para un perfil para cuando se produce un error en la operación de SnapManager.

* *-separate-archivvelog-backups*
+
Especifica que el backup de registros de archivos está separado del backup del archivo de datos. Se trata de un parámetro opcional que puede proporcionar al crear el perfil. Después de separar los backups con esta opción, es posible crear backup solo de archivos de datos o backup de solo registros de archivos.

* *-retain-archivvelog-backups -horas | -daysdays | -weeksweeks| -months*
+
Especifica que los backups de los registros de archivos se retendrán según la duración de la retención de los registros de archivo (horaria, diaria, semanal o mensual).

* *proteger [-protection-polipolypolypolypolypolycoloy_name] | -noprotect*
+
Especifica que los archivos de registro de archivos están protegidos en función de la política de protección del registro de archivos.

+
Especifica que los archivos de registro de archivos no están protegidos mediante la opción -noProtect.

* *-include-with-online-backups | -no-include-with-online-backups*
+
Especifica que el backup de registros de archivos se incluye junto con el backup de la base de datos en línea.

+
Especifica que no se incluyen los backups de registros de archivos junto con el backup de la base de datos en línea.

* *-dump*
+
Especifica que los archivos de volcado no se recopilan después de la operación de creación de perfiles correcta.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. La configuración predeterminada muestra mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.


