---
permalink: unix-administration/reference_the_smosmsap_operation_show_command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, perform, specified, profile, smo, list 
summary: 'Puede ejecutar el comando operation show para mostrar la información de resumen de todas las operaciones realizadas en el perfil especificado. La salida enumera al usuario cliente \(el usuario del PC cliente\) y al usuario efectivo \(el usuario en SnapManager que es válido en el host seleccionado\).' 
---
= El comando smo operation show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando operation show para mostrar la información de resumen de todas las operaciones realizadas en el perfil especificado. La salida muestra el usuario cliente (el usuario del PC cliente) y el usuario efectivo (el usuario de SnapManager que es válido en el host seleccionado).



== Sintaxis

[listing]
----

        smo operation show
-profile profile_name
\[-label label \| -id id\]
\[-quiet \| -verbose\]
----


== Parámetros

* *-profile profile_name*
+
Especifica el nombre del perfil. Este nombre puede tener hasta 30 caracteres y debe ser único dentro del host.

* * etiqueta*
+
Especifica la etiqueta de la operación.

* *-id*
+
Especifica el identificador de la operación.

* *-silencio*
+
Opcional: Muestra solo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Opcional: Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo

La siguiente línea de comandos muestra información detallada sobre una operación:

[listing]
----
# smo operation show -profile myprofile -id ff8080811295eb1c011295eb28230001
----
[listing]
----
Operation Attempted
   Operation ID: ff8080811295eb1c011295eb28230001
   Type:RestoreFor profile: myprofile
   With Force: No
   Performed on backup
   Operation ID: ff8080811295eb1c011296eb23290001
   Label: mylabel
Operation Runtime Information
   Status: SUCCESS
   Start date: 2007-07-16 13:24:09 IST
   End date: 2007-07-16 14:10:10 IST
   Client user: amorrow
   Effective user: amorrow
Host
   Host Run upon: Host3
   Process ID: 3122
   SnapManager version: 3.3
Repository
   Connection: user1@SMOREPO/hotspur:1521
   Repository version: 3.3
Resources in use
   Volume:
     ssys1:/vol/luke_ES0_0 (FlexClone)
   Filesystems:
     /opt/NetApp/smo/mnt/-mnt_ssys1_luke_ES0_smo_e_es0_f_c_1_8abc0112129b0f81580001_0
----
*Información relacionada*

xref:task_viewing_operation_details.adoc[Ver los detalles de la operación]
