---
permalink: unix-administration/reference_the_smosmsapcredential_set_command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, secure, resource, host, repositories, database, profile, specified, argument, smo 
summary: Este comando permite establecer las credenciales para que los usuarios accedan a recursos seguros, como hosts, repositorios y perfiles de bases de datos. La contraseña del host es la contraseña del usuario en el host en el que se ejecuta SnapManager. La contraseña del repositorio es la contraseña del usuario de Oracle que contiene el esquema del repositorio de SnapManager. La contraseña del perfil es una contraseña compuesta por la persona que crea el perfil. Para las opciones de host y repositorio, si no se incluye la opción -password opcional, se le pedirá que introduzca una contraseña del tipo especificado en los argumentos de comando. 
---
= El comando smo credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite establecer las credenciales para que los usuarios accedan a recursos seguros, como hosts, repositorios y perfiles de bases de datos. La contraseña del host es la contraseña del usuario en el host donde se ejecuta SnapManager. La contraseña del repositorio es la contraseña del usuario de Oracle que contiene el esquema del repositorio de SnapManager. La contraseña del perfil es una contraseña compuesta por la persona que crea el perfil. Para las opciones de host y repositorio, si no se incluye la opción -password opcional, se le pedirá que introduzca una contraseña del tipo especificado en los argumentos de comando.



== Sintaxis

[listing]
----

        smo credential set
\[-host
-name host_name
-username username\]
\[-password password\] \] \|
\[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username\] \[-password repo_password\] \]
-port repo_port \|
\[-profile
-name profile_name\]
\[-password password\] \]
\[-quiet \| -verbose\]
----


== Parámetros

* *-host hostname*
+
Especifica el nombre o la dirección IP del servidor host en el que se ejecuta SnapManager.

+
El parámetro -host incluye las siguientes opciones:

+
** -Name host_name: Especifica el nombre del host para el que se establecerá la contraseña.
** -Username user_name: Especifica el nombre de usuario en el host.
** -Password password: Especifica la contraseña del usuario en el host.


* *-repository -dbname*
+
Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.

+
El parámetro -Repository incluye las siguientes opciones:

+
** -Dbnamerepo_service_name: Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.
** -Host repo_host: Especifica el nombre o la dirección IP del servidor host en el que se ejecuta la base de datos de repositorio.
** -Login-username repo_username: Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.
** -Password password: Especifica la contraseña necesaria para acceder a la base de datos que almacena el repositorio.
** -Port repo_Port: Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.


* *-profile -name profile_name*
+
Especifica el perfil con el que está asociada la base de datos.

+
El parámetro -profile incluye la siguiente opción:

+
** -Name profilename: Especifica el nombre del perfil para el que va a configurar la contraseña.
** -Password password: Especifica la contraseña necesaria para acceder al perfil.


* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo de comando para configurar las credenciales del repositorio

En el ejemplo siguiente se establecen credenciales para un repositorio.

[listing]
----

smo credential set -repository -dbname SMOREPO -host hotspur -port 1521 -login -username chris
Password for chris@hotspur:1521/SMOREPO : ********
Confirm password for chris@hotspur:1521/SMOREPO : ********
----
[listing]
----
SMO-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMO-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Ejemplo de comando para configurar las credenciales del host

Dado que las credenciales de host representan una credencial real del sistema operativo, deben incluir el nombre de usuario además de la contraseña.

[listing]
----
smo credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
*Información relacionada*

xref:concept_snapmanager_security.adoc[Cómo mantiene SnapManager la seguridad]
