---
permalink: unix-administration/reference_troubleshooting_known_issues.html 
sidebar: sidebar 
keywords: aware, known, issue, snapmanager, troubleshoot, identify, cluster-mode 
summary: Es necesario conocer algunos problemas conocidos que se pueden producir al utilizar SnapManager y cómo solucionar sus problemas. 
---
= Resolución de problemas conocidos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es necesario conocer algunos problemas conocidos que se pueden producir al utilizar SnapManager y cómo solucionar sus problemas.



== SnapManager para Oracle no identifica los perfiles de modo Cluster

Si el nombre del perfil de Cluster-Mode no está presente en el archivo cmode_profiles.config del directorio de instalación de SnapManager para Oracle, el siguiente mensaje de error podría activarse:

Configure el servidor DFM mediante la configuración de SnapDrive set -dfm user_name Appliance_name.

Además, al actualizar SnapManager para Oracle, si elimina la carpeta /opt/NetApp/smo/*, el archivo cmode_profiles.config que tiene los nombres de perfil de Cluster-Mode también se elimina. Este problema también activa el mismo mensaje de error.

*Solución*

Actualice el perfil: <profile_name> de perfil de actualización de smo


NOTE: Si se instala SnapManager para Oracle en la ruta /opt/NetApp/smo/, la ubicación del archivo es /opt/NetApp/smo/cmode_profile/cmode_profiles.config.



== El servidor no se inicia

Al iniciar el servidor, es posible que aparezca un mensaje de error similar al siguiente:

SMO-01104: Error al invocar el comando: SMO-17107: El servidor SnapManager no se pudo iniciar en el puerto 8074 debido a los siguientes errores: La dirección java.net.BindException: ya está en uso

Esto puede deberse a que los puertos de escucha SnapManager (27214 y 27215, de forma predeterminada) están actualmente en uso en otra aplicación.

Este error también puede ocurrir si el comando smo_Server ya se está ejecutando, pero SnapManager no detecta el proceso existente.

*Solución*

Es posible volver a configurar SnapManager o la otra aplicación para utilizar diferentes puertos.

Para volver a configurar las SnapManager, edite el siguiente archivo: /Opt/NTAP/smo/properties/smo.config

Asigne los siguientes valores:

* Servidor de SMO.Port=27214
* Servidor SMO.rmiRegistry.Port=27215
* remote.registry.ocijdbc.port= 27215
+
El archivo remote.registry.ocijdbc.Port debe ser el mismo que Server.rmiRegistry.Port.



Para iniciar el servidor SnapManager, introduzca el siguiente comando: SMO_Server start


NOTE: Si el servidor ya se está ejecutando, aparecerá un mensaje de error.

Si el servidor ya está en ejecución, realice los siguientes pasos:

. Detenga el servidor introduciendo el siguiente comando: smo_Server stop
. Para reiniciar el servidor, introduzca el siguiente comando: Inicio smo_Server




== Terminando una operación SnapManager en ejecución actualmente

Si el servidor SnapManager se bloquea y no puede ejecutar ninguna operación correctamente, puede finalizar SnapManager y sus operaciones.

*Solución*

SnapManager funciona tanto con SnapManager como con Protection Manager. Debe realizar los siguientes pasos para enumerar los diferentes procesos en ejecución y detener el último proceso en ejecución.

. Enumere todos los procesos de SnapDrive que se están ejecutando: ps
+
Ejemplo: ps | grep SnapDrive

. Detenga el proceso o los procesos de SnapDrive: Kill <pid>
+
pid es la lista de procesos encontrados mediante el comando ps.

+

NOTE: No se detienen todos los procesos de SnapDrive. Se recomienda finalizar solo el último proceso en ejecución.

. Si una de las operaciones implica restaurar un backup protegido desde un almacenamiento secundario, abra la consola de Protection Manager y realice lo siguiente:
+
.. En el menú sistema, seleccione *trabajos*.
.. Seleccione *Restaurar*.
.. Compruebe el nombre del conjunto de datos que coincide con el del perfil de SnapManager.
.. Haga clic con el botón derecho del ratón y seleccione *Cancelar*.


. Enumerar los procesos de SnapManager:
+
.. Inicie sesión como usuario root.
.. Enumerar los procesos mediante el comando ps.
+
Ejemplo: ps | grep java



. Finalizar el proceso de SnapManager: Matar a <pid>




== No se puede eliminar ni liberar la última copia de seguridad protegida

Cuando se crea el primer backup para un perfil en el almacenamiento secundario, SnapManager envía toda la información sobre el backup a Protection Manager. Para backups posteriores relacionados con este perfil, SnapManager solo envía la información modificada. Si se elimina el último backup protegido, SnapManager pierde la capacidad para identificar las diferencias entre los backups y debe buscar una forma de volver a establecer la base de estas relaciones. Por lo tanto, al intentar eliminar la última copia de seguridad protegida se muestra un mensaje de error.

*Solución*

Puede eliminar el perfil o sólo la copia de seguridad del perfil.

Para eliminar el perfil, realice los siguientes pasos:

. Eliminar las copias de seguridad del perfil.
. Actualice el perfil y desactive la protección en el perfil.
+
De esta forma se elimina el conjunto de datos.

. Elimine la última copia de seguridad protegida.
. Elimine el perfil.


Para eliminar solamente el backup, realice los siguientes pasos:

. Cree otra copia de seguridad del perfil.
. Transferir esa copia de backup a almacenamiento secundario.
. Elimine la copia de seguridad anterior.




== No se pueden gestionar los nombres de destino de los archivos de registro de archivos si los nombres de destino forman parte de otros nombres de destino

Al crear una copia de seguridad del registro de archivos, si el usuario excluye un destino que forme parte de otros nombres de destino, también se excluirán los demás nombres de destino.

Por ejemplo, supongamos que hay tres destinos disponibles para ser excluidos: /Dest, /dest1 y /dest2. Al crear el backup del archivo de registro de archivos, si excluye /dest mediante el comando

[listing]
----
smo backup create -profile almsamp1 -data -online -archivelogs  -exclude-dest /dest
----
, SnapManager para Oracle excluye todos los destinos que comiencen con /dest.

*Solución*

* Agregue un separador de ruta después de que los destinos estén configurados en v$archive_dest. Por ejemplo, cambie /dest a /dest/.
* Al crear una copia de seguridad, incluya destinos en lugar de excluir cualquier destino.




== La restauración de archivos de control multiplexados en Automatic Storage Management (ASM) y almacenamiento no ASM falla

Cuando los archivos de control se multiplexan en almacenamiento ASM y no ASM, la operación de copia de seguridad se realiza correctamente. Sin embargo, cuando intenta restaurar archivos de control de ese backup exitoso, se produce un error en la operación de restauración.



== Error en la operación de clonado de SnapManager

Al clonar un backup en SnapManager, es posible que DataFabric Manager Server no detecte volúmenes y muestre el siguiente mensaje de error:

SMO-13032: No se puede realizar la operación: Clone Create. Causa raíz: SMO-11007: Error al clonar desde la instantánea: FLOW-11019: Error al 00018 detectar el almacenamiento para /mnt/DataFile_clon3: SD-10016: Error al ejecutar el comando SnapDrive "/usr/sbin/snapdrive Storage show -fs /mnt/DataFile_clon3": 0002-719 Advertencia: No se pudo comprobar el acceso a 20091122235002515 los servidores de almacenamiento de oracle.x.vol1_vol

Motivo: El recurso especificado no es válido. No se puede encontrar su ID en el servidor de Operations Manager 10.x.x.x.

Esto sucede si el sistema de almacenamiento tiene un gran número de volúmenes.

*Solución*

Debe realizar una de las siguientes acciones:

* Desde el servidor de Data Fabric Manager, ejecute el host dfm Discover Storage_System.
+
También puede añadir el comando en un archivo de script del shell y programar una tarea en DataFabric Manager Server para ejecutar el script a intervalos frecuentes.

* Aumente el valor de dfm-rbac-retries en el archivo SnapDrive.conf.
+
SnapDrive usa el valor del intervalo de actualización predeterminado y la cantidad predeterminada de reintentos. El valor predeterminado de dfm-rbac-retry-sleep-secs es 15 segundos y dfm-rbac-retries es 12 iteraciones.

+

NOTE: El intervalo de actualización de Operations Manager depende del número de sistemas de almacenamiento, del número de objetos de almacenamiento del sistema de almacenamiento y de la carga sobre DataFabric Manager Server.

+
Como recomendación, lleve a cabo lo siguiente:

+
.. En DataFabric Manager Server, ejecute manualmente el siguiente comando para todos los sistemas de almacenamiento secundarios asociados con el conjunto de datos: El host dfm Discover Storage_system
.. Se debe doble el tiempo que se tarda en ejecutar la operación de detección del host y asignar ese valor a dfm-rbac-retry-sleep-secs.
+
Por ejemplo, si la operación tardó 11 segundos, puede establecer el valor de dfm-rbac-retry-sleep-secs en 22 (11*2).







== El tamaño de la base de datos del repositorio crece con el tiempo y no con el número de backups

El tamaño de la base de datos del repositorio crece con el tiempo debido a que las operaciones SnapManager insertan o eliminan datos dentro del esquema en las tablas de la base de datos del repositorio, lo que da como resultado un uso elevado del espacio de índice.

*Solución*

Debe supervisar y reconstruir los índices de acuerdo con las directrices de Oracle para controlar el espacio consumido por el esquema del repositorio.



== No se puede acceder a la interfaz gráfica de usuario de SnapManager y se produce un error en las operaciones de SnapManager cuando la base de datos del repositorio está inactiva

Se produce un error en las operaciones de SnapManager y no se puede acceder a la interfaz gráfica de usuario cuando la base de datos del repositorio está inactiva.

En la siguiente tabla, se enumeran las diferentes acciones que se pueden realizar y sus excepciones:

|===


| Operaciones | Excepciones 


 a| 
Abrir un repositorio cerrado
 a| 
El siguiente mensaje de error se registra en sm_gui.log: [WARN ]: SMO-01106: Se ha producido un error al consultar el repositorio: Closed Connection java.sql.SQLException: Closed Connection.



 a| 
Para actualizar un repositorio abierto, pulse F5
 a| 
Se muestra una excepción de repositorio en la GUI y también registra una NullPointerException en el archivo sm_gui.log.



 a| 
Actualizar el servidor host
 a| 
Se registra una NullPointerException en el archivo sumo_gui.logI.



 a| 
Creación de un nuevo perfil
 a| 
Aparecerá NullPointerException en la ventana Profile Configuration.



 a| 
Actualizar un perfil
 a| 
La siguiente excepción SQL se registra en sm_gui.log: [WARN ]: SMO-01106: Se ha producido un error al consultar el repositorio: Closed Connection.



 a| 
Obtener acceso a un backup
 a| 
El siguiente mensaje de error se registra en sm_gui.log: No se pudo inicializar de forma lazilada una colección.



 a| 
Ver las propiedades de clon
 a| 
El siguiente mensaje de error se registra en sm_gui.log y sumo_gui.log: No se pudo inicializar de forma lazilada una colección.

|===
*Solución*

Debe asegurarse de que se ejecute la base de datos del repositorio cuando se desea acceder a la interfaz gráfica de usuario o realizar cualquier operación de SnapManager.



== No se pueden crear los archivos temporales para la base de datos clonada

Cuando los archivos de espacio de tabla temporales de la base de datos de destino se colocan en puntos de montaje diferentes del punto de montaje de los archivos de datos, la operación de creación de clonado se realiza correctamente, pero SnapManager no puede crear archivos temporales para la base de datos clonada.

*Solución*

Debe realizar una de las siguientes acciones:

* Asegúrese de que la base de datos de destino esté diseñada para que los archivos temporales se coloquen en el mismo punto de montaje que los archivos de datos.
* Crear manualmente o añadir archivos temporales en la base de datos clonada.




== No se puede migrar el protocolo de NFSv3 a NFSv4

Puede migrar el protocolo de NFSv3 a NFSv4 mediante la habilitación del parámetro enable-migrate-nfs-version en el archivo snapdrive.conf. Durante la migración, SnapDrive considera únicamente la versión del protocolo, independientemente de las opciones de punto de montaje como rw, largefiles, nosuid, etc.

Sin embargo, después de migrar el protocolo a NFSv4, cuando restaura el backup creado mediante NFSv3, se produce lo siguiente:

* Si se habilitan NFSv3 y NFSv4 en el nivel de almacenamiento, la operación de restauración se realiza correctamente, pero se monta con las opciones de punto de montaje que estaban disponibles durante el backup.
* Si solo se habilita NFSv4 en el nivel de almacenamiento, la operación de restauración se realiza correctamente y solo se conserva la versión del protocolo (NFSv4).
+
Sin embargo, no se conservan las demás opciones de punto de montaje, como rw, largefiles, nosuid, etc.



*Solución*

Primero debe apagar manualmente la base de datos, desmontar los puntos de montaje de la base de datos y montarlos con las opciones disponibles antes de la restauración.



== Se produce un error en el backup de la base de datos Data Guard en espera

Si se configura alguna ubicación de registro de archivos con el nombre de servicio de la base de datos primaria, se produce un error en el backup de la base de datos en espera de Data Guard.

*Solución*

En la GUI, debe desactivar *especificar la ubicación del registro de archivo externo* correspondiente al nombre de servicio de la base de datos primaria.
