---
permalink: unix-administration/reference_supported_partition_devices.html 
sidebar: sidebar 
keywords: partition, snapmanager, support, device, red, hat, enterprise, linux, 5x, oracle 
summary: Debe conocer los diferentes dispositivos de partición compatibles con SnapManager. 
---
= Dispositivos de partición compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer los diferentes dispositivos de partición compatibles con SnapManager.

La siguiente tabla proporciona información de partición y cómo se puede activar para diferentes sistemas operativos:

|===
| De NetApp | Partición única | Partición múltiple | Dispositivos sin partición | Sistema de archivos o dispositivos RAW 


 a| 
Red Hat Enterprise Linux 5x o

5 veces Oracle Enterprise Linux
 a| 
Sí
 a| 
No
 a| 
No
 a| 
ext3*



 a| 
Red Hat Enterprise Linux 6xor

6 veces Oracle Enterprise Linux
 a| 
Sí
 a| 
No
 a| 
No
 a| 
ext3 o ext4*



 a| 
SUSE Linux Enterprise Server 11
 a| 
Sí
 a| 
No
 a| 
No
 a| 
ext3*



 a| 
SUSE Linux Enterprise Server 10
 a| 
No
 a| 
No
 a| 
Sí
 a| 
ext3***



 a| 
Red Hat Enterprise Linux 5x o posterioresor

Oracle Enterprise Linux 5 o posterior
 a| 
Sí
 a| 
No
 a| 
Sí
 a| 
ASM con ASMLib**



 a| 
SUSE Linux Enterprise Server 10 SP4or

SUSE Linux Enterprise Server 11
 a| 
Sí
 a| 
No
 a| 
Sí
 a| 
ASM con ASMLib**



 a| 
SUSE Linux Enterprise Server 10 SP4 o posteror

SUSE Linux Enterprise Server 11
 a| 
Sí
 a| 
No
 a| 
No
 a| 
ASM sin ASMLib****

|===
Para obtener más información sobre las versiones compatibles del sistema operativo, consulte la matriz de interoperabilidad.
