---
permalink: unix-administration/reference_the_smosmsapbackup_create_command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smo 
summary: El comando backup create permite crear backups de base de datos en uno o varios sistemas de almacenamiento. 
---
= El comando smo backup create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El comando backup create permite crear backups de base de datos en uno o varios sistemas de almacenamiento.



== Sintaxis


NOTE: Antes de ejecutar este comando, debe crear un perfil de base de datos mediante el comando profile create.

[listing]
----

        smo backup create
-profile profile_name
{\[-full\{-auto \| -online \| -offline\}\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\]  |
\[-data \[\[-files files \[files\]\] \|
\[-tablespaces tablespaces \[tablespaces\]\] \[-label label\] \{-auto \| -online \| -offline\}
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\] |
\[-archivelogs \[-label label\]\] \[-comment comment\]}
\[-protect \| -noprotect \| -protectnow\]
\[-backup-dest path1 \[ , path2\]\]
\[-exclude-dest path1 \[ , path2\]\]
\[-prunelogs \{-all \| -until-scn until-scn \| -until-date yyyy-MM-dd:HH:mm:ss\] \| -before \{-months \| -days \| -weeks \| -hours}}
-prune-dest prune_dest1,\[prune_dest2\]\]
\[-taskspec taskspec\]
\[-dump\]
-force
\[-quiet \| -verbose\]
----


== Parámetros

* *-profile profile_name*
+
Especifica el nombre del perfil relacionado con la base de datos de la que desea realizar backup. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *-opción automática*
+
Si la base de datos está en estado montado o sin conexión, SnapManager realiza un backup sin conexión. Si la base de datos está en estado abierto o en línea, SnapManager realiza un backup en línea. Si se utiliza la opción -force con la opción -offline, SnapManager fuerza un backup sin conexión aunque la base de datos esté actualmente en línea.

* *-opción en línea*
+
Especifica un backup de base de datos en línea.

+
Es posible crear un backup en línea de una base de datos de Real Application Clusters (RAC), siempre que el primario se encuentre en estado abierto o el primario se monte y una instancia se encuentre en estado abierto. Puede utilizar la opción -force para backups en línea si la instancia local está en estado de apagado o no hay ninguna instancia en estado abierto. La versión de Oracle debe ser 10.2.0.5; de lo contrario, la base de datos se bloqueará si existe alguna instancia en el RAC montada.

+
** Si la instancia local está en estado de apagado y al menos una instancia está en estado abierto, puede utilizar la opción -force para cambiar la instancia local al estado montado.
** Si ninguna instancia está en estado abierto, puede utilizar la opción -force para cambiar la instancia local al estado abierto.


* *-opción sin conexión*
+
Especifica una copia de seguridad sin conexión mientras la base de datos está en estado de apagado. Si la base de datos está en estado abierto o montado, el backup genera errores. Si se utiliza la opción -force, SnapManager intenta modificar el estado de la base de datos para cerrar la base de datos con el fin de realizar una copia de seguridad sin conexión.

* *-opción completa*
+
Realiza un backup de toda la base de datos. Esto incluye todos los datos, registros archivados y archivos de control. Se realiza una copia de seguridad de los redo logs archivados y de los archivos de control, independientemente del tipo de copia de seguridad que realice. Si se desea realizar un backup solo de una parte de la base de datos, se deben utilizar la opción -files o -tablespaces.

* *-opción de datos*
+
Especifica los archivos de datos.

* *-lista de archivos*
+
Realiza un backup solo de los archivos de datos especificados, además de los archivos de registro y control archivados. Separe la lista de nombres de archivo con espacios. Si la base de datos se encuentra en estado abierto, SnapManager verifica que los espacios de tablas apropiados se encuentren en modo de backup en línea.

* *-tablespaces*
+
Realiza un backup solo de los espacios de tablas de la base de datos especificados, además de los archivos de registro y control archivados. Separe los nombres de tablespace con espacios. Si la base de datos se encuentra en estado abierto, SnapManager verifica que los espacios de tablas apropiados se encuentren en modo de backup en línea.

* * etiqueta*
+
Especifica un nombre opcional para este backup. Este nombre debe ser único dentro del perfil. El nombre puede contener letras, números, guiones bajos (_) y guiones (-). No puede comenzar con un guión. Si no se especifica una etiqueta, SnapManager crea una etiqueta predeterminada en el formato scope_type_date:

+
** El ámbito es F indicar un backup completo o P para indicar un backup parcial.
** El tipo es C para indicar una copia de seguridad sin conexión (en frío), H para indicar una copia de seguridad en línea (activa) o A para indicar una copia de seguridad automática, por ejemplo, P_A_20081010060037IST.
** Fecha es el año, el mes, el día y la hora de la copia de seguridad.
+
SnapManager se usa un reloj de 24 horas.



+
Por ejemplo, si realizó un backup completo con la base de datos sin conexión el 16 de enero de 2007, a las 5:45:16 Hora estándar del este, SnapManager crearía la etiqueta F_C_20070116174516EST.

* *-cadena de comentario*
+
Especifica un comentario opcional para describir esta copia de seguridad. La cadena debe escribirse entre comillas simples (').

+

NOTE: Algunos vaciados despegan las comillas. En este caso, se debe incluir la comillas con una barra diagonal inversa (\). Por ejemplo, es posible que deba introducir la siguiente información: `\' this is a comment\'`.

* *-verificar opción*
+
Verifica que los archivos de la copia de seguridad no están dañados ejecutando la utilidad oracle dbv.

+

NOTE: Si se especifica la opción -Verify, la operación de backup no se completará hasta que finalice la operación de verificación.

* *-opción de fuerza*
+
Fuerza un cambio de estado si la base de datos no está en el estado correcto. Por ejemplo, SnapManager puede cambiar el estado de la base de datos de en línea a sin conexión, según el tipo de backup especificado y el estado en el que está la base de datos.

+
Con un backup de base de datos de RAC en línea, utilice la opción -force si la instancia local está en estado apagado o no hay ninguna instancia en estado abierto.

+

NOTE: La versión de Oracle debe ser 10.2.0.5; de lo contrario, la base de datos se bloqueará si existe alguna instancia en el RAC montada.

+
** Si la instancia local está en estado de apagado y al menos una instancia está en estado abierto, el uso de la opción -force cambia la instancia local al estado montado.
** Si ninguna instancia está en el estado abierto, con la opción -force , la instancia local cambia al estado abierto.


* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.

* *-protect | -noprotect | -protectadow*
+
Indica si el backup debe protegerse a un almacenamiento secundario. La opción -noProtect especifica que el backup no debe protegerse en el almacenamiento secundario. Solo se protegen los backups completos. Si se especifica ninguna de las dos opciones, SnapManager protege el backup como predeterminado si el backup es un backup completo y el perfil especifica una política de protección. La opción -protectnow sólo se aplica a Data ONTAP en 7-Mode. La opción especifica que el backup se proteja inmediatamente en el almacenamiento secundario.

* *-retener { -hora | -diario | -semanal | -mensual | -ilimitado}*
+
Especifica si el backup se debe retener por hora, día, semana, mes o ilimitada. Si no se especifica la opción -retain, la clase de retención predeterminada es la opción -Hourly. Para retener las copias de seguridad para siempre, utilice la opción -Unlimited. La opción -Unlimited hace que el backup no sea apto para que lo elimine la política de retención.

* *-archivelogs opción*
+
Crea un backup de registro de archivos.

* *-backup-más extraño path1, [, [path2]]*
+
Especifica los destinos de registros de archivos que se incluirán en el backup para el backup de registros de archivos.

* *-exclude-más extraño path1, [, [path2]]*
+
Especifica los destinos de registro de archivos que se excluirán de la copia de seguridad.

* *-prunelogs {-all | -until-scnuntil-scn | -until-dateyyyy-MM-dd:HH:mm:ss | -before {-meses | -días | -semanas | -horas}*
+
Elimina los archivos de registro de archivos de los destinos de registro de archivos según las opciones proporcionadas al crear un backup. La opción -all elimina todos los archivos de registro de archivos de los destinos de registro de archivos. La opción -until-scn elimina los archivos de registro de archivos hasta que se especifique un número de cambio de sistema (SCN). La opción -until-date elimina los archivos de registro de archivos hasta el periodo de tiempo especificado. La opción -before elimina los archivos de registro de archivos antes del periodo de tiempo especificado (días, meses, semanas, horas).

* *-prune-dest prune_dest1,prune_dest2*
+
Elimina los archivos de registro de archivos de los destinos de registro de archivos mientras se crea el backup.

* *-tasktaskspec*
+
Especifica el archivo XML de especificación de la tarea que se puede utilizar para la actividad de preprocesamiento o la actividad de posprocesamiento de la operación de copia de seguridad. Se debe proporcionar la ruta completa del archivo XML al proporcionar la opción -taskspec .

* *-opción de volcado*
+
Recoge los archivos de volcado después de una operación de backup de base de datos con errores o realizada correctamente.





== Comando de ejemplo

El siguiente comando crea un backup completo en línea, crea un backup en el almacenamiento secundario y establece la política de retención en diaria:

[listing]
----
smo backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
*Información relacionada*

xref:task_creating_database_backups.adoc[Creación de backups de la base de datos]

xref:reference_the_smosmsapprofile_create_command.adoc[El comando smo profile create]

xref:concept_restoring_protected_backups_from_secondary_storage.adoc[Restaurar backups protegidos a partir del almacenamiento secundario]
