---
permalink: unix-administration/reference_the_smosmsapclone_template_command.html 
sidebar: sidebar 
keywords: command, create, clone, specification, template, smo 
summary: Este comando permite crear una plantilla de especificación de clon. 
---
= El comando de plantilla de clon de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite crear una plantilla de especificación de clon.



== Sintaxis

[listing]
----

        smo clone template
-profile name
\[-backup-id guid  \| -backup-label backup_name\]
\[-quiet \| -verbose\]
----


== Parámetros

* *-nombre del perfil*
+
Especifica la base de datos que desea crear una especificación de clon de. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *-backup-id guid*
+
Crea una especificación de clon a partir del backup con el GUID especificado. SnapManager genera el GUID cuando se crea un backup. Utilice el comando smo backup list para mostrar el GUID de cada backup.

* *-backup-label backup_label_name*
+
Crea una especificación de clonado a partir del backup con la etiqueta de backup especificada.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el siguiente ejemplo, se crea una plantilla de especificación de clon a partir del backup con la etiqueta full_backup_sales_May. Una vez completado el comando de plantilla de clon de smo, la plantilla de especificación del clon se completa.

[listing]
----
smo clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
*Información relacionada*

xref:task_creating_clone_specifications.adoc[Creando especificaciones de clon]

xref:task_cloning_databases_from_backups.adoc[Clonar bases de datos a partir de backups]
