---
permalink: unix-administration/reference_the_smosmsap_repository_rollingback_command.html 
sidebar: sidebar 
keywords: command, enable, rollback, revert, higher, version, snapmanager, original, version, upgrade, smo, repository 
summary: Este comando permite revertir o revertir una versión superior de SnapManager a la versión original desde la que se actualizó. 
---
= El comando rollback del almacén de smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite revertir o revertir una versión superior de SnapManager a la versión original desde la que se actualizó.



== Sintaxis

[listing]
----

        smo repository rollback
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
-rollbackhost host_with_target_database
[-force]
\[-quiet \| -verbose\]
----


== Parámetros

* *-repositorio*
+
Las opciones que siguen a -repository especifican los detalles de la base de datos para el repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el repositorio. Utilice el nombre global o el SID.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *-login*
+
Inicia los detalles de inicio de sesión en el repositorio.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.

* *-rollbackhost host host_with_target_database*
+
Especifica el nombre del host que se va a revertir de una versión superior de SnapManager a la versión anterior original.

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *-fuerza*
+
Intenta forzar la actualización del repositorio. SnapManager le solicita que realice una copia de seguridad del repositorio actual antes de la actualización.

* *-noprompt*
+
No muestra el mensaje antes de actualizar la base de datos del repositorio. El uso de la opción -noprompt garantiza que no aparezca la petición de datos, lo que facilita la actualización de repositorios mediante una secuencia de comandos.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el ejemplo siguiente se actualiza el repositorio de la base de datos SALESDB.

[listing]
----
smo repository rollback -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -rollbackhost hostA
----