---
permalink: unix-administration/reference_product_overview.html 
sidebar: sidebar 
keywords: snapmirror, oracle, automate, simplifies, complex, manual, time-consuming, process, backup, recover, clone, technologies, aoracle, real, application, clusters, rac 
summary: SnapManager para Oracle automatiza y simplifica los procesos manuales asociados a operaciones como el backup, la recuperación y el clonado de bases de datos de Oracle, tareas de gran complejidad y que requieren mucho tiempo. Puede usar SnapManager con la tecnología SnapMirror de ONTAP para crear copias de backups en otro volumen, y también con la tecnología ONTAP SnapVault para archivar backups de forma eficiente a disco. 
---
= Información general del producto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager para Oracle automatiza y simplifica los procesos manuales asociados a operaciones como el backup, la recuperación y el clonado de bases de datos de Oracle, tareas de gran complejidad y que requieren mucho tiempo. Puede usar SnapManager con la tecnología SnapMirror de ONTAP para crear copias de backups en otro volumen, y también con la tecnología ONTAP SnapVault para archivar backups de forma eficiente a disco.

SnapManager se integra con tecnologías nativas de Oracle como Real Application Clusters (Oracle RAC), Automatic Storage Management (ASM) y Direct NFS en protocolos FC, iSCSI y NFS. De manera opcional, los backups creados mediante SnapManager se pueden catalogar con Oracle RMAN para conservar la información de backups; estos backups se pueden utilizar posteriormente en operaciones de restauración a nivel de bloque o recuperación a un momento específico de espacio de tabla.



== Aspectos destacados de SnapManager

SnapManager integra perfectamente con las bases de datos Oracle en el host UNIX y es gracias a las tecnologías de copias Snapshot, SnapRestore y FlexClone de NetApp Ofrece una interfaz de usuario (UI) fácil de usar y una interfaz de línea de comandos (CLI) para funciones administrativas.

SnapManager permite realizar las siguientes operaciones de base de datos y gestionar los datos de forma eficiente:

* Creación de backups con gestión eficiente del espacio en almacenamiento primario o secundario
+
Es posible realizar un backup de los archivos de datos y los archivos de registro de archivos por separado.

* Programación de backups
* Restauración de bases de datos completas o parciales mediante una operación de restauración basada en archivos o volúmenes
* Recuperación de bases de datos mediante la detección, el montaje y la aplicación de archivos de registro de archivos a partir de backups
* Eliminar archivos de registro de archivos de destinos de registro de archivos cuando se crean backups solo de los registros de archivos
* Si se conserva un número mínimo de backups de registros de archivos automáticamente, solo se deben retener los backups que contienen archivos únicos de registro de archivos
* Realizar un seguimiento de los detalles de las operaciones y generar informes
* Verificación de copias de seguridad para garantizar que las copias de seguridad tienen un formato de bloque válido y que ninguno de los archivos de copia de seguridad está dañado
* Mantener un historial de operaciones realizadas en el perfil de base de datos
+
Un perfil contiene información acerca de la base de datos que va a gestionar SnapManager.

* Crear clones de backups con gestión eficiente del espacio en sistemas de almacenamiento principales o secundarios
+
SnapManager permite dividir el clon de una base de datos.


