---
permalink: unix-administration/reference_the_smosmsapprofile_update_command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, existing, profile, smo 
summary: Puede ejecutar el comando profile update para actualizar la información de un perfil existente. 
---
= El comando smo profile update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el comando profile update para actualizar la información de un perfil existente.



== Sintaxis

[listing]
----

        smo profile update
-profile profile
\[-new-profile new_profile_name\]
\[-profile-password profile_password\]
[-database
-dbname db_dbname
-host db_host
\[-sid db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 \[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]
[\{-rman  \{-controlfile \| \{\{-login
-username  rman_username
-password  rman_password \}
\[-tnsname  tnsname\]\}\}\} \|
-remove-rman\]
-osaccount osaccount
-osgroup osgroup
[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-patternpattern
[-protect \[-protection-policy policy_name\] \| \[-noprotect\]]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name\] \| \[-noprotect\]]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== Parámetros

Si se ha establecido una política de protección en el perfil, no podrá cambiar la política con SnapManager. Debe cambiar la política con la consola de Protection Manager.

* * perfil*
+
Especifica el nombre del perfil. Este nombre puede tener hasta 30 caracteres y debe ser único dentro del host.

* *-profile-password profile_password*
+
Especifica la contraseña del perfil.

* *-new-profile new_profile_name*
+
Especifica el nuevo nombre que puede proporcionar para un perfil.

* *-base de datos*
+
Especifica los detalles de la base de datos que describe el perfil. Esta es la base de datos de la que se realizará un backup, se restaurará, etc.

* *-dbname db_dbname*
+
Especifica el nombre de la base de datos que describe el perfil. Es posible usar el nombre global o el identificador del sistema.

* *-host db_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos.

* *-sid db_sid*
+
Especifica el identificador del sistema de la base de datos que describe el perfil. De forma predeterminada, SnapManager utiliza el nombre de la base de datos como identificador del sistema. Si el identificador del sistema es diferente del nombre de la base de datos, debe especificarlo mediante la opción -sid.

+
Por ejemplo, si utiliza Real Application Clusters (RAC) de Oracle, debe especificar el identificador de sistema SID de la instancia de RAC en el nodo RAC desde el cual se ejecuta SnapManager.

* *-login*
+
Especifica los detalles de inicio de sesión del repositorio.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos del repositorio.

* *-port repo_port*
+
Especifica el número de puerto TCP necesario para acceder a la base de datos del repositorio.

* *-base de datos*
+
Especifica los detalles de la base de datos que describe el perfil. Esta es la base de datos que se realizará un backup, se restaurará o se clonará.

* *-dbname db_dbname*
+
Especifica el nombre de la base de datos que describe el perfil. Es posible usar el nombre global o el identificador del sistema.

* *-host db_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos.

* *-login*
+
Especifica los detalles de inicio de sesión de la base de datos.

* *-username db_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que describe el perfil.

* *-password db_password*
+
Especifica la contraseña necesaria para acceder a la base de datos que describe el perfil.

* *-puerto db_port*
+
Especifica el número de puerto TCP necesario para acceder a la base de datos que describe el perfil.

* *-asminstance*
+
Especifica las credenciales que se utilizan para iniciar sesión en la instancia de Automatic Storage Management (ASM).

* *-asmusername asminstance_username*
+
Especifica el nombre de usuario utilizado para iniciar sesión en la instancia de ASM.

* *-asmpassword asminstance_password*
+
Especifica la contraseña utilizada para iniciar sesión en la instancia de ASM.

* *-rman*
+
Especifica los detalles que utiliza SnapManager para catalogar los backups con Oracle Recovery Manager (RMAN).

* *-controllfile*
+
Especifica los archivos de control de la base de datos de destino en lugar de un catálogo como repositorio de RMAN.

* *-login*
+
Especifica los detalles de inicio de sesión de RMAN.

* *-password rman_password*
+
Especifica la contraseña que se utiliza para iniciar sesión en el catálogo de RMAN.

* *-username rman_username*
+
Especifica el nombre de usuario utilizado para iniciar sesión en el catálogo de RMAN.

* *-tnsname tnsname*
+
Especifica el nombre de conexión tnsname (que se define en el archivo tsname.ora).

* *-remove-rman*
+
Especifica la eliminación de RMAN en el perfil.

* *-osaccount*
+
Especifica el nombre de la cuenta de usuario de la base de datos Oracle. SnapManager utiliza esta cuenta para realizar operaciones de Oracle como el inicio y el apagado. Generalmente, es el usuario propietario del software de Oracle en el host, por ejemplo, oracle.

* *-osgroup osgroup*
+
Especifica el nombre del grupo de base de datos Oracle asociado a la cuenta de oracle.

* *-retener [-contador hora [-compensn] [-duración m]] [-diario [-conteo n] [-duración m] [-semanal [-conteo n][-duración m]] [-mensual [-conteo n][-duración m]]*
+
Especifica la clase de retención (por hora, por día, por semana o por mes) para una copia de seguridad.

+
Para cada clase de retención, se puede especificar un recuento de retención, una duración de retención o ambas. La duración se encuentra en unidades de la clase (por ejemplo, horas por hora o días por día). Por ejemplo, si el usuario especifica solo una duración de retención de 7 para backups diarios, SnapManager no limitará la cantidad de backups diarios del perfil (ya que el número de retención es 0), pero SnapManager eliminará automáticamente los backups diarios creados hace más de 7 días.

* *-comentario*
+
Especifica el comentario de un perfil.

* *-snapname-pattern patrón*
+
Especifica el patrón de nomenclatura para las copias Snapshot. También puede incluir texto personalizado, por ejemplo, HOPS para operaciones altamente disponibles, en todos los nombres de copias Snapshot. Puede cambiar el patrón de nomenclatura de las copias Snapshot al crear un perfil o después de crear el perfil. El patrón actualizado se aplica solo a las copias snapshot que aún no se han producido. Las copias Snapshot que existen conservan el patrón Snapname anterior. Puede utilizar varias variables en el texto del patrón.

* *-protect [-protection-polipolypolypolypolycoloy_name] | [-noprotect]*
+
Indica si el backup debe protegerse a un almacenamiento secundario o no.

+

NOTE: Si -Protect se especifica sin -protection-policy, el conjunto de datos no tendrá una política de protección. Si se especifica -Protect y -protection-policy no se establece cuando se crea el perfil, puede ser establecido más tarde comando bysmo profile update o establecido por el administrador de almacenamiento mediante la consola de Protection Manager .

+
La opción -noProtect especifica no proteger el perfil para el almacenamiento secundario.

* *-resumen-notificación*
+
Especifica que la notificación de resumen por correo electrónico está activada para el perfil existente.

* *-notificación [-success-email e-mail_dirección1,dirección de e-mail.2 -subject_pattern]*
+
Habilita la notificación de correo electrónico para el perfil existente de forma que los destinatarios reciban los correos electrónicos cuando la operación SnapManager se realice correctamente. Debe introducir una única dirección de correo electrónico o varias direcciones de correo electrónico a las que se enviarán las alertas por correo electrónico y un patrón de asunto del correo electrónico para el perfil existente.

+
Puede cambiar el texto del asunto al actualizar el perfil o incluir texto de asunto personalizado. El asunto actualizado sólo se aplica a los correos electrónicos que no se envían. Puede usar varias variables para el asunto del correo electrónico.

* *-notificación [-failure -email e-mail_dirección1,dirección de e-mail.2 -subject_pattern]*
+
Habilita la notificación de correo electrónico para el perfil existente de modo que los destinatarios reciban los correos electrónicos cuando falle la operación de SnapManager. Debe introducir una única dirección de correo electrónico o varias direcciones de correo electrónico a las que se enviarán las alertas por correo electrónico y un patrón de asunto del correo electrónico para el perfil existente.

+
Puede cambiar el texto del asunto al actualizar el perfil o incluir texto de asunto personalizado. El asunto actualizado sólo se aplica a los correos electrónicos que no se envían. Puede usar varias variables para el asunto del correo electrónico.

* *-separate-archivvelog-backups*
+
Separa el backup de registros de archivos del backup de archivo de datos. Este es un parámetro opcional que puede proporcionar al crear el perfil. Después de separar los backups se separan con esta opción, es posible crear un backup de solo los archivos de datos o un backup de solo los registros de archivos.

* *-retain-archivvelog-backups -horas | -daysdays | -weeksweeks| -months*
+
Especifica que los backups de los registros de archivos se retendrán según la duración de la retención del registro de archivos (hora, día, semana, mensual).

* *-protect [-protection-polipolypolypolypolycoloy_name] | -noprotect*
+
Especifica que los archivos de registro de archivos están protegidos en función de la política de protección del registro de archivos.

+
Especifica que los archivos de registro de archivos no están protegidos mediante la opción -noProtect.

* *-include-with-online-backups | -no-include-with-online-backups*
+
Especifica que el backup de registros de archivos se incluye junto con el backup de la base de datos en línea.

+
Especifica que no se incluyen los backups de registros de archivos junto con el backup de la base de datos en línea.

* *-dump*
+
Especifica que los archivos de volcado se recopilan después de la operación de creación de perfiles correcta.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo

En el ejemplo siguiente se cambia la información de inicio de sesión de la base de datos descrita por el perfil y se configura la notificación por correo electrónico para este perfil:

[listing]
----
smo profile update -profile SALES1 -database -dbname SALESDB
 -sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----
*Información relacionada*

xref:task_changing_profile_passwords.adoc[Cambio de contraseñas de perfil]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[Cómo SnapManager retiene los backups en el almacenamiento local]
