---
permalink: unix-administration/reference_the_smosmsaprepository_delete_command.html 
sidebar: sidebar 
keywords: command, delete, repository, store, database, profile, associate, credentials, smo 
summary: Este comando elimina un repositorio utilizado para almacenar perfiles de base de datos y credenciales asociadas. Sólo puede eliminar un repositorio si no hay perfiles en el repositorio. 
---
= El comando smo repository delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando elimina un repositorio utilizado para almacenar perfiles de base de datos y credenciales asociadas. Sólo puede eliminar un repositorio si no hay perfiles en el repositorio.



== Sintaxis

[listing]
----

        smo repository delete
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----


== Parámetros

* *-repositorio*
+
Las opciones que siguen a -repository especifican los detalles de la base de datos para el repositorio.

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el repositorio. Utilice el nombre global o el SID.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *-login*
+
Inicia los detalles de inicio de sesión en el repositorio.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.

* *-fuerza*
+
Se intenta forzar la eliminación del repositorio, incluso si hay operaciones incompletas. SnapManager emite un aviso si existen operaciones incompletas, en las que se pregunta si está seguro de que se desea eliminar el repositorio.

* *-noprompt*
+
No se le solicita antes de eliminar el repositorio. El uso de la opción -noprompt garantiza que no aparezca la petición de datos, lo que facilita la eliminación de repositorios mediante una secuencia de comandos.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo de comando

En el ejemplo siguiente se elimina el repositorio de la base de datos SALESDB.

[listing]
----
smo repository delete -repository -port 1521 -dbname smorep
-host nila -login -username smofresno -force -verbose
This command will delete repository "smofresno@smorep/nila".
Any resources maintained by the repository must be cleaned up manually.
This may include snapshots, mounted backups, and clones.
Are you sure you wish to proceed (Y/N)?Y
[ INFO] SMO-09201: Dropping existing schema as smofresno
  on jdbc:oracle:thin:@//nila:1521/smorep.
[ INFO] SMO-13048: Repository Delete Operation Status: SUCCESS
[ INFO] SMO-13049: Elapsed Time: 0:00:06.372
[ INFO] SMO-20010: Synchronizing mapping for profiles in
   repository "smofresno@smorep/nila:1521".
[ WARN] SMO-20029: No repository schema exists in "smofresno@smorep/nila:1521".
 Deleting all profile mappings for this repository.
[ INFO] SMO-20012: Deleted stale mapping for profile "TESTPASS".
----