---
permalink: unix-administration/reference_the_smosmsaprepository_create_command.html 
sidebar: sidebar 
keywords: smo, repository, creat, command 
summary: Este comando crea un repositorio en el que se almacenan perfiles de base de datos y credenciales asociadas. 
---
= El comando smo repository create
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Sintaxis

Este comando crea un repositorio en el que se almacenan perfiles de base de datos y credenciales asociadas. Este comando también comprueba si el tamaño de los bloques es adecuado.

[listing]
----

        smo repository create
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
\[-quiet \| -verbose\]
----


== Parámetros

* *-repositorio*
+
Las opciones que siguen a -repository especifican los detalles de la base de datos para el repositorio

* *-port repo_port*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *-dbname repo_service_name*
+
Especifica el nombre de la base de datos que almacena el repositorio. Utilice el nombre global o el SID.

* *-host repo_host*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *-login*
+
Inicia los detalles de inicio de sesión en el repositorio.

* *-username repo_username*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.

* *-fuerza*
+
Se intenta forzar la creación del repositorio. Con esta opción, SnapManager se solicita que se realice un backup del repositorio antes de crear el repositorio.

* *-noprompt*
+
No muestra el símbolo del sistema de realizar una copia de seguridad del repositorio antes de crearlo si utiliza la opción -force. El uso de la opción -noprompt garantiza que el prompt no aparezca, facilitando la creación de repositorios con un script.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo de comando

El siguiente ejemplo crea un repositorio en la base de datos SMOREPO en el hotspur del host.

[listing]
----
smo repository create -repository -port 1521 -dbname SMOREPO -host hotspur -login -username grabal21 -verbose
SMO-09202 [INFO ]: Creating new schema as grabal21 on jdbc:oracle:thin:@//hotspur:1521/SMOREPO.
SMO-09205 [INFO ]: Schema generation complete.
SMO-09209 [INFO ]: Performing repository version INSERT.
SMO-09210 [INFO ]: Repository created with version: 30
SMO-13037 [INFO ]: Successfully completed operation: Repository Create
SMO-13049 [INFO ]: Elapsed Time: 0:00:08.844
----