---
permalink: unix-administration/reference_the_smosmsapbackup_verify_command.html 
sidebar: sidebar 
keywords: run, backup, verify, command, format, oracle, valid, smo 
summary: Es posible ejecutar el comando backup verify para ver si el backup está en un formato válido para Oracle. 
---
= El comando smo backup verify
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible ejecutar el comando backup verify para ver si el backup está en un formato válido para Oracle.



== Sintaxis

[listing]
----

        smo backup verify
-profile profile_name
[-label backup_name \| \[-id guid\]
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\}\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----


== Parámetros

* *-profile profile_name*
+
Especifica el perfil para el que desea verificar un backup. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *-id guid*
+
Verifica el backup con el GUID especificado. SnapManager genera el GUID cuando se crea un backup. Puede utilizar el comando smo backup list para mostrar el GUID de cada backup.

* *-label label_name*
+
Verifica el backup con la etiqueta especificada.

* *-dump*
+
Recopila los archivos de volcado después de la operación de verificación de backup realizada correctamente o con errores.

* *-fuerza*
+
Fuerza a la base de datos al estado necesario para realizar la operación de verificación.

* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo

A continuación se muestra un ejemplo de verificación del backup:

[listing]
----
smo backup verify -profile SALES1 -label full_backup_sales_May -quiet
----
[listing]
----
DBVERIFY - Verification starting : FILE = +SMO_1_1161675083835/smo/datafile/data.277.582482539 ...
----
*Información relacionada*

xref:task_verifying_database_backups.adoc[Verificación de los backups de las bases de datos]
