---
permalink: unix-administration/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smo 
summary: Este comando elimina las credenciales de usuario de un recurso protegido en particular. 
---
= El comando smo credential delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando elimina las credenciales de usuario de un recurso protegido en particular.



== Sintaxis

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== Parámetros

* *-host hostname*
+
Especifica el nombre del servidor host en el que se ejecuta SnapManager.

+
El parámetro -host incluye las siguientes opciones:

+
** -Name host_name: Especifica el nombre del host para el que se eliminará la contraseña.
** -Username user_name: Especifica el nombre de usuario en el host.


* *-repository -dbname*
+
Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.

+
El parámetro -Repository incluye las siguientes opciones:

+
** -Dbnamerepo_service_name: Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.
** -Host repo_host: Especifica el nombre o la dirección IP del servidor host en el que se ejecuta la base de datos de repositorio.
** -Login-username repo_username: Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.
** -Port repo_Port: Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.


* *-profile -name profile_name*
+
Especifica el perfil con el que está asociada la base de datos.

+
El parámetro -profile incluye la siguiente opción:

+
** -Name profilename: Especifica el nombre del perfil para el que se eliminará la contraseña.


* *-silencio*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *-verbose*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En este ejemplo se eliminan las credenciales del perfil.

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
En este ejemplo, se eliminan las credenciales del repositorio.

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
En este ejemplo, se eliminan las credenciales del host.

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
*Información relacionada*

xref:task_deleting_credentials_for_individual_resources.adoc[Eliminación de credenciales para recursos individuales]
