---
permalink: unix-administration/task_cloning_protected_backups.html 
sidebar: sidebar 
keywords: snapmanager, clone, copy, backup, protect, cloning, san, nas, ontap, 7-mode 
summary: Es posible usar SnapManager para clonar una copia de un backup que se ha protegido. 
---
= Clonar backups protegidos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar SnapManager para clonar una copia de un backup que se ha protegido.

El host (seleccionado para el clon) debe tener acceso al almacenamiento secundario con el mismo protocolo de almacenamiento (por ejemplo, SAN o NAS).

Es posible usar la opción -from-secondary para especificar que se desea clonar desde el almacenamiento secundario.

Debe especificar la opción -copy-id siempre que especifique la opción -from-secondary. Si existe más de un backup en el sistema de almacenamiento secundario, la opción -copy-id se utiliza para especificar qué copia de backup en el almacenamiento secundario se debe usar para clonar.


NOTE: Si se utiliza Data ONTAP en 7-Mode, es necesario especificar un valor válido para la opción -copy-id. Sin embargo, si utiliza Clustered Data ONTAP, la opción -copy-idOption no es necesaria.

Puede producirse un error al eliminar clones de backups protegidos en sistemas de almacenamiento secundario. Este problema se produce cuando la hora del sistema de los sistemas de almacenamiento primario y secundario no están sincronizados.

. Cree un clon de una copia de backup protegida: smo clone create -backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile-from-secondary -copy-idid




== Ejemplo

[listing]
----
smo clone create -label testdb_clone_clstest
-profile sys_db_finance -from-secondary -copy-id 3042 sys_db_finance_sept_08
----