---
permalink: unix-administration/task_adding_existing_profile_to_summary_notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, exist, profile, summary, email, notification, updating, profile 
summary: SnapManager le permite añadir un perfil existente a una notificación de correo electrónico de resumen al actualizar dicho perfil. 
---
= Adición de un perfil existente para resumir las notificaciones por correo electrónico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager le permite añadir un perfil existente a una notificación de correo electrónico de resumen al actualizar dicho perfil.

. Introduzca el siguiente comando: smo profile update -profileprofile_name [-profile-passwordprofile_password] -repository_service_name-hotrepo_portrepo_Port-login-usernamerepo [-nombre_base-nombredbedb_dbedb_nombre_nombre_nombre_host] [-did_did]-nombre_nombre_usuario]-did-diserb]-nombre_nombre_usuariob] [-nombre_nombre_nombre_usuariob]-nombre_nombre_usuariob]-nombredeusuario]-nombre_nombre_nombre_nombre_usuariob]-nombre_nombre_nombre_nombre_nombre_nombre_usuariob] [-nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_usuariob]]-nombre_nombre_nombre_nombre_nombre_usuariob]-nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_archivo]]-nombre_usuariob] [-nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre_nombre

