---
permalink: unix-administration/task_performing_a_rollback_on_a_single_host_or_multiple_hosts.html 
sidebar: sidebar 
keywords: perform, rollback, single, multiple, snapmanager, server, host, command-line, interface, cli 
summary: 'Puede realizar una reversión en uno o varios hosts de servidor SnapManager utilizando la interfaz de línea de comandos \(CLI\).' 
---
= Ejecución de una reversión en un solo host o varios hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar una reversión en una sola o varios hosts de servidor SnapManager con la interfaz de línea de comandos (CLI).

Se debe asegurarse de que se hayan completado todos los requisitos previos para realizar una reversión.

. Para realizar una reversión en un solo host, introduzca el siguiente comando:
`smorepository rollback-repository-dbnamerepo_service_name-hostrepo_host-login-usernamerepo_username-portrepo_port-rollbackhosthost_with_target_database`
+
En el ejemplo siguiente se muestra el comando para revertir todas las bases de datos de destino montadas en Hosta y una base de datos de repositorio denominada REPOA ubicada en el host de repositorio, repo_host:

+
[listing]
----

smo repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA
----
. Para realizar una reversión en varios hosts, introduzca el siguiente comando: Smorepostory rollback-repository-dbnamerepo_service_name-hostrepo_host-login-usernamerepo_username-portrepo_Port-rollbackhoshost_with_target_database1,host_with_target_target_database2
+

NOTE: Si desea introducir varios hosts, introduzca los nombres de host separados por una coma y asegúrese de que no haya espacio entre la coma y el siguiente nombre de host.

+
Si utiliza una configuración de RAC, debe revertir manualmente todos los hosts asociados de RAC. Es posible utilizar -allhosts para realizar una reversión de todos los hosts.

+
En el ejemplo siguiente se muestra el comando para revertir todas las bases de datos de destino montadas en los hosts, Hosta, HostB y una base de datos de repositorio denominada REPOA ubicada en el host de repositorios, repo_host:

+
[listing]
----

smo repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA,hostB
----
+
Los hosts, los perfiles, las programaciones, los backups y los clones que están asociados con los perfiles de las bases de datos de destino para el host se revierten al repositorio anterior.



*Información relacionada*

xref:concept_prerequisites_for_performing_a_rollback.adoc[Requisitos previos para ejecutar una reversión]
