---
permalink: unix-administration/task_configuring_summary_e_mail_notification_for_multiple_profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, configure, summary, email, notification, multiple, profile, repository, database 
summary: SnapManager permite configurar una notificación por correo electrónico de resumen para varios perfiles en una base de datos de repositorio. 
---
= Configuración de notificación por correo electrónico de resumen para varios perfiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager permite configurar una notificación por correo electrónico de resumen para varios perfiles en una base de datos de repositorio.

Es posible configurar el host del servidor SnapManager como host de notificación desde el cual se envía el correo electrónico de notificación de resumen a los destinatarios. Si se cambian el nombre de host o la dirección IP del servidor SnapManager, también se puede actualizar el host de notificación.

Puede seleccionar cualquiera de las horas de programación en las que se requiera una notificación por correo electrónico:

* Hourly: Para recibir una notificación por correo electrónico cada hora
* Diario: Para recibir una notificación por correo electrónico diariamente
* Semanal: Para recibir una notificación por correo electrónico semanalmente
* Mensual: Recibir una notificación por correo electrónico mensualmente


Debe introducir una sola dirección de correo electrónico o una lista de direcciones de correo electrónico separadas por comas para recibir notificaciones de las operaciones realizadas mediante dichos perfiles. Asegúrese de que no haya espacio entre la coma y la siguiente dirección de correo electrónico cuando introduzca varias direcciones de correo electrónico.

SnapManager le permite añadir un asunto de correo electrónico personalizado utilizando las siguientes variables:

* Nombre de perfil utilizado para la operación de base de datos.
* Nombre de la base de datos
* SID de la base de datos
* Nombre del servidor host
* Hora de inicio de la operación de la base de datos en el formato yyyymmdd:hh:ss
* Hora de finalización de la operación de la base de datos en el formato yyyymmdd:hh:ss
* Estado de la operación de base de datos


Si selecciona no agregar un asunto personalizado, SnapManager muestra un mensaje de error: Falta valor -asunto.

. Introduzca el siguiente comando: Notificación de smo update-summary-notification -repository-portrepo_Port-dbnamerepo_service_name-hstrepo_host-login-usernamerepo_username-emailmail_dirección1,email_directs2-subjectSubject-patterm-frequency {-day-profiletime_time | -1|3-time|4|31-time|1-time|5|6-time|7-time|1-time|1-time||1-time|1-time||-time|1-time|1-time|1-time|1||1-time|1-time|1|-time|-time|1-time|
+
Las demás opciones para este comando son las siguientes:

+
[-force] [-noprompt]

+
[quiet | -verbose]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email-address admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1 -notification-host wales
----

