---
permalink: unix-administration/task_deleting_backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, occupy, remove, reduce, deleting, clone 
summary: Debe eliminar backups cuando ya no los necesite, lo que libera el espacio que estos backups ocupan. Si elimina los backups, reducirá la posibilidad de alcanzar el límite de 255 copias snapshot por volumen. 
---
= Eliminar backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe eliminar backups cuando ya no los necesite, lo que libera el espacio que estos backups ocupan. Si elimina los backups, reducirá la posibilidad de alcanzar el límite de 255 copias snapshot por volumen.

* Debe asegurarse de que el backup no se haya usado para crear un clon.


Cuando se elimina un backup protegido, SnapManager elimina el backup del almacenamiento secundario y el repositorio de SnapManager. En la siguiente tabla, se muestran las acciones emprendidas en el almacenamiento primario y secundario al eliminar un backup local:

|===
| Estado de protección | Estado local | De datos en cuanto al almacenamiento primario | Acción en el almacenamiento secundario | Explicación 


 a| 
No solicitado (protegido)
 a| 
Existe
 a| 
Elimina las copias Snapshot
 a| 
No se requiere ninguna acción
 a| 
SnapManager eliminará el backup local.



 a| 
Liberado
 a| 
No se requiere ninguna acción
 a| 
No se requiere ninguna acción
 a| 
La copia de seguridad local ya está liberada. Si se elimina un backup liberado, los metadatos del backup se eliminan del repositorio.
 a| 
Sin proteger



 a| 
Existe
 a| 
Elimina las copias Snapshot
 a| 
No se requiere ninguna acción
 a| 
SnapManager elimina el backup local tanto si se ha protegido como si no.
 a| 
Liberado



 a| 
No se requiere ninguna acción
 a| 
No se requiere ninguna acción
 a| 
La copia de seguridad local ya está liberada. Si se elimina un backup liberado, los metadatos del backup se eliminan del repositorio.
 a| 
Protegido
 a| 
Existe



 a| 
Elimina las copias Snapshot
 a| 
SnapManager elimina el backup en el almacenamiento secundario
 a| 
SnapManager elimina el backup local y las copias secundarias.
 a| 
Liberado
 a| 
No se requiere ninguna acción

|===
Si intenta eliminar un backup que está protegido por el almacenamiento secundario, es posible que las copias de Snapshot se marquen para eliminarse y, posteriormente, Protection Manager las elimina.

Puede eliminar backups retenidos de forma ilimitada sin cambiar la clase de retención.

Opcionalmente, es posible recoger los archivos de volcado después de la operación de eliminación de backup exitosa o con errores.

Si desea eliminar los backups de registros de archivos, debe comprobar la duración de retención establecida para el backup de registros de archivos. Si el backup de registros de archivos se encuentra dentro de la duración de retención y se requieren archivos de registro de archivos para la recuperación de una base de datos restaurada, no se puede eliminar el backup de registros de archivos.

. Para verificar que las operaciones se han completado, introduzca el siguiente comando: smo operation list -profileprofile_name-quiet-verbose
. Para eliminar una copia de seguridad, introduzca el siguiente comando:copia de seguridad de smo delete -profile profile_name [-label label label label [data | -archivvelogs] | -idid | -all] [-force] [-dump] [-quiet | -verbose]
+
Utilice la opción -force para forzar la eliminación del backup. Forzar la eliminación de un backup que tenga operaciones incompletas podría dejar el backup en estado incoherente.


