---
permalink: unix-administration/task_viewing_clone_split_estimate.html 
sidebar: sidebar 
keywords: clone, split, estimate, help, total, free, space, available, aggregate, amount, space, share, smo 
summary: La estimación de división de clones ayuda a conocer el espacio libre total disponible en el agregado, la cantidad de espacio compartido entre el clon y la base de datos original, y el espacio utilizado exclusivamente por el clon. Además, puede ver la fecha y la hora en que se creó el clon subyacente y la antigüedad del clon. Según esta estimación, usted decide si dividir un clon o no. 
---
= Ver una estimación de división de clones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La estimación de división de clones ayuda a conocer el espacio libre total disponible en el agregado, la cantidad de espacio compartido entre el clon y la base de datos original, y el espacio utilizado exclusivamente por el clon. Además, puede ver la fecha y la hora en que se creó el clon subyacente y la antigüedad del clon. Según esta estimación, usted decide si dividir un clon o no.

Para ver la estimación de división de clones, debe introducir el nombre del perfil del clon original y la etiqueta o GUID de la operación de clonado. Si el clon está en otro host, es posible especificar el nombre de host.

. Para ver la estimación de división de clones, introduzca el siguiente comando:
`smo clone split-estimate -profileprofile [-hosthostname] [-labelclone-label | -idclone-id][-quiet | -verbose]`


En el siguiente ejemplo, se muestra el comando para la estimación de almacenamiento de división de clones:

[listing]
----
smo clone split-estimate

-profile p1 -label clone_test_label
----