---
permalink: unix-administration/task_configuring_snapdrive_when_rbac_is_not_enabled.html 
sidebar: sidebar 
keywords: register, root, user, administrator, datafabric, manager, server, root, user, storage, system, snapdrive, rbac 
summary: Para habilitar la protección de datos, debe registrar en SnapDrive al usuario raíz o al administrador de DataFabric Manager Server y al usuario raíz del sistema de almacenamiento. 
---
= La configuración de SnapDrive cuando RBAC no está habilitado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar la protección de datos, debe registrar en SnapDrive al usuario raíz o al administrador de DataFabric Manager Server y al usuario raíz del sistema de almacenamiento.

. Para actualizar DataFabric Manager Server para actualizar los cambios realizados directamente en el sistema de almacenamiento mediante la base de datos de destino, introduzca el siguiente comando:
+
host dfm detecte storage_system

. Para registrar el usuario raíz o el administrador de DataFabric Manager Server en SnapDrive, introduzca el siguiente comando:
+
SnapDrive config set -dfm Administratordfm_host

. Para registrar el usuario raíz o el administrador del sistema de almacenamiento con SnapDrive, escriba el siguiente comando:
+
configuración de SnapDrive establezca root storage_system


