---
permalink: unix-administration/task_configuring_e_mail_notification_for_an_existing_profile.html 
sidebar: sidebar 
keywords: updating, profile, configure, receive, email, notification, completion, database, operation, exist, comma-seperated, list 
summary: Al actualizar un perfil, puede configurar para recibir una notificación por correo electrónico al finalizar la operación de la base de datos. 
---
= Configuración de la notificación por correo electrónico para un perfil existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al actualizar un perfil, puede configurar para recibir una notificación por correo electrónico al finalizar la operación de la base de datos.

* Debe configurar la dirección de correo electrónico desde la cual se envían las alertas.
* Debe introducir una sola dirección de correo electrónico o varias direcciones de correo electrónico a las que se enviarán las alertas.
+
Puede usar una lista separada por comas para varias direcciones. Debe asegurarse de que no hay espacio entre la coma y la siguiente dirección de correo electrónico. Si lo desea, también puede añadir un asunto al correo electrónico.

+
.. Introduzca el siguiente comando:patterns profile update -profileprofile [-profile-passwordprofile_password][-database-dbnombrecompensb_dbname-host dB_host [-siddb_sid] [-login -usernamedb_username-password_password-Port_host] [{-direcciónn_email]-posess]-direcciónn-email]-nombredeusuario [-posseurb]-nombredeusuario]
+
La opción Success se puede utilizar para recibir una notificación únicamente sobre las operaciones de base de datos correctas y la opción Failure para recibir una notificación solo sobre las operaciones de base de datos fallidas.




