---
permalink: unix-administration/task_configuring_snapdrive_in_an_active_active_unix_environment.html 
sidebar: sidebar 
keywords: include, host-cluster-sw-restore-warn, parameter, snapdrive.conf, assign, value, change, snapdrive, unix, veritas, sfrac, environment 
summary: 'Si ha incluido el parámetro host-cluster-sw-restore-warn en snapdrive.conf y ha asignado el valor on, debe cambiar el valor para admitir la operación de restauración en el entorno activo/activo de Veritas Storage Foundation para Oracle RAC \(SFRAC\).' 
---
= Configuración de SnapDrive para UNIX para un entorno activo/activo de Veritas SFRAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha incluido el parámetro host-cluster-sw-restore-warn en snapdrive.conf y ha asignado el valor on, debe cambiar el valor para admitir la operación de restauración en el entorno activo/activo de Veritas Storage Foundation para Oracle RAC (SFRAC).

Cuando se utiliza el entorno Active/active Veritas Storage Foundation para Oracle RAC (SFRAC), si el parámetro host-cluster-sw-restore-warn está activado, se muestra un mensaje de advertencia y se detiene la operación de restauración. Si desea realizar la operación de restauración en un entorno Veritas SFRAC activo/activo, debe establecer host-cluster-sw-restore-warn en OFF.

Para obtener más información sobre snapdrive.conf, consulte la documentación de SnapDrive.

. Inicie sesión como usuario root.
. Abra el archivo snapdrive.conf mediante un editor de texto.
. Cambie el valor host-cluster-sw-restore-warn a OFF.


Tras la configuración, reinicie el servidor SnapDrive para UNIX.

http://mysupport.netapp.com/["Documentación en el sitio de soporte de NetApp: mysupport.netapp.com"]
