---
permalink: unix-administration/task_adding_storage_systems_to_the_snapmanager_server_host.html 
sidebar: sidebar 
keywords: add, storage, system, operating, clustered, data, ontap, snapmanager, server, host, enable, autosupport 
summary: Debe añadir los sistemas de almacenamiento operativos en Clustered Data ONTAP al host del servidor de SnapManager para habilitar AutoSupport. En SnapManager 3.3 y versiones anteriores, AutoSupport solo era compatible con sistemas de almacenamiento que funcionaban en 7-Mode. 
---
= Añadir sistemas de almacenamiento que funcionen en Clustered Data ONTAP al host del servidor SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe añadir los sistemas de almacenamiento operativos en Clustered Data ONTAP al host del servidor de SnapManager para habilitar AutoSupport. En SnapManager 3.3 y versiones anteriores, AutoSupport solo era compatible con sistemas de almacenamiento que funcionaban en 7-Mode.

. Añada sistemas de almacenamiento que funcionen en Clustered Data ONTAP al host del servidor SnapManager.
+
|===
| Si... | Después, ejecute el siguiente comando... 


 a| 
La máquina virtual de almacenamiento de administración (SVM, antes denominada Vserver) está funcionando en Clustered Data ONTAP
 a| 
SnapDrive config set -cserver user_namestorage_name



 a| 
SVM opera en Clustered Data ONTAP
 a| 
SnapDrive config set -vserver usuario_namestorage_name

|===

