---
permalink: unix-administration/task_mounting_backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, rman, 7-mode 
summary: 'SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También puede montar copias de seguridad en situaciones en las que utilice una herramienta externa, como Oracle Recovery Manager \(RMAN\), para acceder a los archivos de la copia de seguridad.' 
---
= Montar backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También es posible montar backups en situaciones en las que se utilice una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad.

Si utiliza RMAN, debe utilizar la operación de montaje para cambiar el estado de un backup (que permite el acceso) y la operación de desmontaje para cambiar el estado de un backup (que quita el acceso).

El comando smo backup Mount muestra una lista de rutas donde se han montado las copias Snapshot consistentes en el backup.

Puede usar la opción -from-secondary para montar el backup desde el almacenamiento secundario. Si no utiliza esta opción, SnapManager monta el backup desde el almacenamiento principal.

Debe especificar la opción -copy-id siempre que especifique la opción -from-secondary. Si existe más de un backup en el sistema de almacenamiento secundario, la opción -copy-id se utiliza para especificar qué copia de backup en el almacenamiento secundario se debe utilizar para montar el backup.6


NOTE: Si se utiliza Data ONTAP en 7-Mode, es necesario especificar un valor válido para la opción -copy-id. Sin embargo, si utiliza Clustered Data ONTAP, la opción -copy-id no es necesaria.

Si va a montar un backup de base de datos en un host remoto, debe asegurarse de que las credenciales de Automatic Storage Management (ASM) sean las mismas en ambos hosts.


NOTE: Opcionalmente, es posible recoger los archivos de volcado después de una operación de montaje de backup exitosa o con errores.

. Para montar un backup, introduzca el siguiente comando:
`smo backup mount -profile profile_name {labellabel [data | -archivelogs] | -idid} [-host-host] [-from-secondary [-copy-id id]] [-dump] [-quiet | -verbose]`


*Información relacionada*

xref:reference_the_smosmsapbackup_mount_command.adoc[El comando de montaje de backup de smo]
