---
permalink: unix-administration/task_cloning_databases_from_backups.html 
sidebar: sidebar 
keywords: clone, database, backup, using, clone, create, command, sid, snapmanager 
summary: Es posible clonar una base de datos a partir de un backup con el comando clone create. 
---
= Clonar bases de datos a partir de backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible clonar una base de datos a partir de un backup con el comando clone create.

Primero debe crear un archivo de especificación del clon para la base de datos. SnapManager crea el clon según la información de este archivo de especificación.

Debe proporcionar al clon un nuevo identificador del sistema de Oracle (SID). No se pueden ejecutar dos bases de datos con el mismo SID simultáneamente en el mismo host. Puede tener un clon en otro host que utiliza el mismo SID. Para designar un nombre único para el clon, utilice -label. Si no utiliza esta opción, SnapManager crea un nombre único para el clon que incluye el SID, fecha y hora.

Después de clonar una base de datos, es posible que desee actualizar los archivos tnsnames.ora en los equipos cliente con la nueva información de conexión de base de datos clonada. Los archivos tnsnames.ora se utilizan para conectarse a una instancia de Oracle sin tener que especificar la información completa de la base de datos. SnapManager no actualiza los archivos tnsnames.ora.

SnapManager siempre crea un backup, incluidos los archivos de registro de archivos, si se utiliza el perfil creado con backups -include-con-en-línea. SnapManager permite clonar únicamente los backups completos de la base de datos.

SnapManager (3.2 o posterior) permite clonar los backups que contienen los archivos de datos y los archivos de registro de archivos.

Si el registro de archivos está disponible desde una ubicación externa, puede especificar la ubicación externa durante la clonado para recuperar la base de datos clonada en un estado coherente. Debe asegurarse de que Oracle pueda acceder a la ubicación externa. No se admite la clonado de backups de solo registro de archivos.

Aunque se crea el backup de registros de archivos junto con el backup parcial en línea, no se puede crear un clon de la base de datos con este backup.

Es posible clonar el backup de base de datos desde la ubicación de archivo de registro de archivos externo solo para una base de datos independiente.

Se produce un error en la clonado del backup de la base de datos en línea de la base de datos de Real Application Clusters (RAC) mediante la ubicación del archivo de registro de archivos externo debido a un fallo en la recuperación. Esto se debe a que la base de datos de Oracle no puede encontrar y aplicar los archivos de registro de archivos para la recuperación desde la ubicación del registro de archivos externo al clonar el backup de la base de datos.

Puede especificar la opción -dump como un parámetro opcional para recoger los archivos de volcado después de la operación de creación de clones con errores o correctamente.

*Clonación de copia de seguridad de archivo de datos sin copia de seguridad de archivo de registro*

Cuando el backup de archivos de datos no incluye el backup de registros de archivo, SnapManager para Oracle clona la base de datos según el número de cambio del sistema (SCN) registrado durante el backup. Si no se puede recuperar la base de datos clonada, se muestra el mensaje de error archivo de registro archivado de <number> de subproceso y <SCN> de cambio necesario para completar la recuperación, a pesar de que SnapManager para Oracle sigue clonando la base de datos y, finalmente, se realiza correctamente la creación del clon.

Al clonar con el backup de archivos de datos sin incluir el backup de registros de archivos, SnapManager recupera la base de datos clonada hasta el último SCN de registro de archivos, que se registra durante el backup.

. Cree un archivo de especificación del clon.
. Para crear un clon, introduzca el siguiente comando: smo clone create -backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecpath_to_clonespecfile [-taskspectaskspec] [-recover-from-location] path1 [,<path2>...][-dump]]


*Información relacionada*

xref:task_cloning_databases_in_the_current_state.adoc[Clonado de bases de datos en estado actual]

xref:concept_considerations_for_cloning_a_database_to_an_alternate_host.adoc[Consideraciones para clonar una base de datos en un host alternativo]

xref:task_creating_clone_specifications.adoc[Creando especificaciones de clon]

xref:reference_the_smosmsapclone_create_command.adoc[El comando smo clone create]

xref:task_creating_pretask_post_task_and_policy_scripts.adoc[Crear scripts de tareas previas, tareas posteriores y directivas]

xref:concept_variables_available_in_the_task_scripts_for_clone_operation.adoc[Variables disponibles en los scripts de tareas para la operación de clonado]

xref:task_creating_task_scripts.adoc[Creación de scripts de tareas]

xref:task_storing_the_task_scripts.adoc[Almacenamiento de los scripts de tareas]
