---
permalink: unix-administration/task_customizing_the_email_subject_for_an_existing_profile.html 
sidebar: sidebar 
keywords: snapmanager, enable, customize, email, subject, pattern, exist, profile, smo 
summary: SnapManager le permite personalizar el patrón de asunto del correo electrónico para un perfil existente actualizando dicho perfil. Este patrón de asunto personalizado sólo es aplicable al perfil actualizado. 
---
= Personalización del asunto del correo electrónico para un perfil existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager le permite personalizar el patrón de asunto del correo electrónico para un perfil existente actualizando dicho perfil. Este patrón de asunto personalizado sólo es aplicable al perfil actualizado.

. Introduzca el siguiente comando: smo profile update -profileprofile [-profile-passwordprofile_password][-database-dbnombrecompensb_dbname-host dB_host [-siddb_sid] [-login -usernamedb_username-password_password-Port_host] [{-dirección-nombredeusuario] [-nombredeusuario_archivo_archivo]]-contraseña]-archivo_archivo_correo-archivo]-archivo-archivo-archivo-archivo-archivo-archivo] [-archivo-archivo-archivo-archivo]-archivo-archivo]-archivo-archivo-archivo-archivo]-archivo-archivo-archivo]-archivo-archivo-archivo-archivo-archivo-archivo]-archivo-archivo-archivo-archivo]-archivo-archivo-archivo-archivo-archivo]-archivo-archivo-archivo-archivo-archivo-archivo-archivo]-archivo-archivo-archivo-archivo-archivo-archivo]-archivo-archivo-archivo-archivo-archivo-archivo-archivo]-archivo-archivo-archivo-archivo-archivo-archivo [_archivo-archivo-archivo-archivo-archivo-archivo-archivo-archivo-archivo]-archivo-archivo


En el siguiente ejemplo se muestra un patrón de asunto del correo electrónico:

[listing]
----

smo profile update -profile sales1 -profile-password sales1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----