---
permalink: unix-administration/task_customizing_e_mail_subject_for_a_new_profile.html 
sidebar: sidebar 
keywords: customize, email, subject, new, profile, create 
summary: Puede personalizar el asunto del correo electrónico para el nuevo perfil cuando lo cree. 
---
= Personalización del asunto del correo electrónico para un nuevo perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede personalizar el asunto del correo electrónico para el nuevo perfil cuando lo cree.

Puede personalizar el asunto del correo electrónico utilizando el patrón \{profile}_\{operation-name}_\{dB-sid}_\{dB-host}_\{start-date}_\{end-date}_\{status} o bien introducir su propio texto.

|===
| Nombre de la variable | Descripción | Valor de ejemplo 


 a| 
perfil
 a| 
Nombre de perfil utilizado para la operación de base de datos
 a| 
PROF1



 a| 
nombre-operación
 a| 
Nombre de la operación de base de datos
 a| 
Backup, copia de seguridad de datos, copia de seguridad de registros de datos y archivos



 a| 
db-sid
 a| 
SID de la base de datos
 a| 
DB1



 a| 
host de base de datos
 a| 
Nombre del servidor host
 a| 
Hosta



 a| 
fecha de inicio
 a| 
La hora de inicio de la operación de la base de datos en el formato mdd:hh:ss yyyy
 a| 
Abril 27 21:00:45 PST 2012



 a| 
fecha de finalización
 a| 
Hora de finalización de la operación de la base de datos en el formato mdd:hh:ss yyyy
 a| 
Abril 27 21:10:45 PST 2012



 a| 
estado
 a| 
Estado de la operación de base de datos
 a| 
Correcto

|===
Si no se proporciona ningún valor para las variables, SnapManager muestra el siguiente mensaje de error: Faltan valores -Subject.

. Introduzca el siguiente comando: smo profile create -profileprofile [-profile-passwordprofile_password] -repository [-dbnamercompenspo_service_name-hotrepo_host_portrepo_Port-login-usernamerpo [-name]-directory [-nombre_nombre_usuario]-nombredehost [-did_nombre_usuario]-nombredeusuario] [-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario-nombredearchivo] [-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario-nombredearchivo] [-nombredeusuario-nombredeusuario-nombredeusuario]-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario] [-nombredeusuario-nombredeusuario]-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario-nombredearchivo] [-nombredeusuario-nombredeusuario-nombredeusuario] [-nombredeusuario-nombredeusuario-nombredeusuario-nombredeusuario] [-d.


A continuación se muestra un ejemplo que muestra el patrón del asunto del correo electrónico:

[listing]
----

smo profile create -profile sales1 -profile-password admin1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----