---
permalink: unix-installation-cmode/task_verifying_the_oracle_listener_configuration.html 
sidebar: sidebar 
keywords: listener, process, listen, client, connection, request, receive, incoming, client, request, traffic, status, listener, configuration 
summary: El listener es un proceso que escucha las solicitudes de conexión de cliente. Recibe solicitudes entrantes de conexión de cliente y administra el tráfico de estas solicitudes a la base de datos. Antes de conectarse a una base de datos de destino o a una instancia de base de datos de repositorio, puede utilizar el comando STATUS para comprobar la configuración del listener. 
---
= Verificación de la configuración del listener de Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El listener es un proceso que escucha las solicitudes de conexión de cliente. Recibe solicitudes entrantes de conexión de cliente y administra el tráfico de estas solicitudes a la base de datos. Antes de conectarse a una base de datos de destino o a una instancia de base de datos de repositorio, puede utilizar el comando STATUS para comprobar la configuración del listener.

El comando STATUS muestra información básica sobre el estado de un listener específico, incluyendo un resumen de la configuración del listener, las direcciones del protocolo de escucha y un resumen de los servicios registrados con ese listener.

. Introduzca el siguiente comando en el símbolo del sistema:
`lsnrctl STATUS`
+
El valor predeterminado asignado al puerto de escucha es 1521.


